import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as THREE from '../dist/tactics/vendor/three.module.js';
import {createLightHorse} from '../dist/tactics/horse-light-model.js';
import {surfaceComponents} from '../dist/tactics/grey-surface.js';
for(const profile of [{file:'horse-light-data.json',budget:30000,error:.006001},{file:'horse-10k-data.json',budget:10500,error:.010001}]){
const data=JSON.parse(fs.readFileSync(new URL('../dist/tactics/'+profile.file,import.meta.url)));
test(profile.file+': closed and connected within triangle budget',()=>{assert.ok(data.triangles<profile.budget);assert.ok(data.triangles<data.sourceTriangles*.04);for(const p of data.parts){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p.position,3));g.setIndex(p.index);assert.equal(surfaceComponents(g),1,p.name);const edges=new Map();for(let i=0;i<p.index.length;i+=3)for(let j=0;j<3;j++){const a=p.index[i+j],b=p.index[i+(j+1)%3],key=Math.min(a,b)+':'+Math.max(a,b);assert.notEqual(a,b);edges.set(key,(edges.get(key)||0)+1);}for(const n of edges.values())assert.equal(n,2,p.name);assert.ok(p.errorWorld<=profile.error);g.dispose();}});
test(profile.file+': weighted neutral mesh reproduces the stored form and every skin weight is valid',()=>{const h=createLightHorse(data);try{assert.equal(h.bones.length,17);for(const m of h.parts){assert.ok(m.isSkinnedMesh);const a=m.geometry.attributes;for(let i=0;i<a.position.count;i++){let sum=0;for(let k=0;k<4;k++){const w=a.skinWeight.array[i*4+k],b=a.skinIndex.array[i*4+k];assert.ok(w>=0&&w<=1);assert.ok(b<h.bones.length);sum+=w;}assert.ok(Math.abs(sum-1)<1e-6);const p=new THREE.Vector3().fromBufferAttribute(a.position,i),actual=m.applyBoneTransform(i,p.clone());assert.ok(actual.distanceTo(p)<1e-6);for(const v of [a.uv.getX(i),a.uv.getY(i)])assert.ok(v>=0&&v<=1);}}const d=h.diagnostics();assert.ok(Math.abs(d.max[1]-1.65)<1e-6);assert.ok(Math.abs(d.min[1])<1e-7);}finally{h.dispose();}});
test(profile.file+': carry deforms actual arms, keeps feet planted and puts hand geometry around independent rifle grips',()=>{const h=createLightHorse(data);try{h.pose('carry');const d=h.diagnostics();assert.ok(Math.abs(d.min[1])<1e-7);assert.equal(d.contacts.length,2);for(const c of d.contacts){assert.ok(c.error<1e-6);const m=h.parts.find(p=>p.name==='forearm and hand '+c.side),v=new THREE.Vector3(),target=new THREE.Vector3(...c.grip);let nearest=Infinity,motion=0;for(let i=0;i<m.geometry.attributes.position.count;i++){v.fromBufferAttribute(m.geometry.attributes.position,i);const original=v.clone();m.applyBoneTransform(i,v);motion=Math.max(motion,v.distanceTo(original));if(original.y<.77)nearest=Math.min(nearest,v.distanceTo(target));}assert.ok(motion>.1);assert.ok(nearest<.015,`hand ${c.side} nearest grip surface ${nearest}`);}const muzzle=h.rifle.anchors.muzzle.getWorldPosition(new THREE.Vector3()),p=h.rifle.barrel.geometry.attributes.position;let closest=Infinity;for(let i=0;i<p.count;i++)closest=Math.min(closest,new THREE.Vector3().fromBufferAttribute(p,i).applyMatrix4(h.rifle.barrel.matrixWorld).distanceTo(muzzle));assert.ok(closest<1e-6);h.pose('neutral');assert.ok(Math.abs(h.diagnostics().max[1]-1.65)<1e-6);}finally{h.dispose();}});

}
