import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as THREE from '../dist/tactics/vendor/three.module.js';
import {createPigForeman} from '../dist/tactics/pig-foreman.js';
import {paintCoordinates,PAINT_FRAME} from '../dist/tactics/horse-model-paint.js';
import {surfaceComponents} from '../dist/tactics/grey-surface.js';
const load=file=>JSON.parse(fs.readFileSync(new URL('../dist/tactics/'+file,import.meta.url)));
const author=load('pig-foreman-author-data.json'),reduced=load('pig-foreman-10k-data.json');
function geometry(p){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p.position,3));g.setIndex(p.index);return g;}
for(const data of [author,reduced]){
 test(`${data.triangles}: closed connected surfaces, scale and species landmarks survive reduction`,()=>{
  assert.ok(data.triangles<=(data===author?30000:10500));assert.equal(data.parts.length,9);
  for(const p of data.parts){const g=geometry(p);assert.equal(surfaceComponents(g),1,p.name);const edges=new Map();for(let i=0;i<p.index.length;i+=3)for(let j=0;j<3;j++){const a=p.index[i+j],b=p.index[i+(j+1)%3];assert.notEqual(a,b);const key=Math.min(a,b)+':'+Math.max(a,b);edges.set(key,(edges.get(key)||0)+1);}for(const n of edges.values())assert.equal(n,2,p.name);assert.ok(p.errorWorld<.0035);g.dispose();}
  const h=createPigForeman(data);try{const d=h.diagnostics();assert.ok(Math.abs(d.min[1])<1e-6);assert.ok(Math.abs(d.max[1]-1.65)<.002);
   const skull=h.parts[6],cap=h.parts[8];skull.geometry.computeBoundingBox();cap.geometry.computeBoundingBox();assert.ok(skull.geometry.boundingBox.max.z>.22&&skull.geometry.boundingBox.min.z<-.22,'folded ears extend beyond skull');assert.ok(cap.geometry.boundingBox.max.y>1.64,'service cap completes standing height');assert.ok(cap.geometry.boundingBox.max.x>.19,'projecting visor');
   // A hanging lobe dips below the outward corner; the rejected wedge
   // monotonically narrowed and never formed this curved lower silhouette.
   for(const side of [-1,1]){const p=skull.geometry.attributes.position,lobe=[],corner=[],profile=[];for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i)*side;if(x<0&&y>1.35){if(z>.185&&z<.215)lobe.push(y);if(z>.245&&z<.26)corner.push(y);if(z>.18&&y>1.38)profile.push(x);}}assert.ok(lobe.length&&corner.length);assert.ok(Math.min(...lobe)<Math.min(...corner)-.025,'rounded lower lobe below outward ear corner');assert.ok(Math.max(...profile)-Math.min(...profile)>.075,'flap has depth sweep visible in profile');}
   const tail=h.parts[7];assert.match(tail.name,/tail/);tail.geometry.computeBoundingBox();assert.ok(tail.geometry.boundingBox.min.x<-.30);assert.ok(tail.geometry.boundingBox.max.y<.92,'small curled tail');const si=tail.geometry.attributes.skinIndex,sw=tail.geometry.attributes.skinWeight;for(let i=0;i<si.count;i++){assert.equal(si.getX(i),0);assert.equal(sw.getX(i),1);}
   const ray=new THREE.Raycaster();const hits=[];for(const z of [0,.031,-.031]){ray.set(new THREE.Vector3(.4,1.432,z),new THREE.Vector3(-1,0,0));const hit=ray.intersectObject(skull)[0];assert.ok(hit);hits.push(hit.point.x);}assert.ok(hits[0]>hits[1]+.007&&hits[0]>hits[2]+.007,'two nostrils recessed in the flat snout');
   for(const side of [-1,1]){const boot=h.parts.find(p=>p.name==='work boot '+side);for(const dz of [0,-.035,.035]){ray.set(new THREE.Vector3(.4,.025,side*.232+dz),new THREE.Vector3(-1,0,0));const hit=ray.intersectObject(boot)[0];assert.ok(hit&&hit.point.x>.13,'solid forward sole, not a split hoof');}}
  }finally{h.dispose();}
 });
 test(`${data.triangles}: normalized rig, fixed feet, independent rifle grips and neutral restoration`,()=>{const h=createPigForeman(data);try{assert.equal(h.bones.length,17);for(const m of h.parts){const a=m.geometry.attributes;for(let i=0;i<a.position.count;i++){let sum=0;for(let k=0;k<4;k++){const w=a.skinWeight.array[i*4+k];assert.ok(w>=0&&w<=1);sum+=w;}assert.ok(Math.abs(sum-1)<1e-6);const p=new THREE.Vector3().fromBufferAttribute(a.position,i);assert.ok(m.applyBoneTransform(i,p.clone()).distanceTo(p)<1e-6);}}
   for(const heading of [0,37,90,173,225,315]){h.pose('carry',heading);const d=h.diagnostics();assert.ok(Math.abs(d.min[1])<1e-6);assert.equal(d.contacts.length,2);for(const c of d.contacts){assert.ok(c.error<1e-6);const m=h.parts.find(p=>p.name==='forearm and hand '+c.side),a=m.geometry.attributes.position,grip=new THREE.Vector3(...c.grip);let distance=Infinity;for(let i=0;i<a.count;i++)if(a.getY(i)<.77){const p=new THREE.Vector3().fromBufferAttribute(a,i);m.applyBoneTransform(i,p);p.applyMatrix4(m.matrixWorld);distance=Math.min(distance,p.distanceTo(grip));}assert.ok(distance<.016,'actual hand surface near independent rifle grip');}}
   h.pose('carry');const chest=h.parts[0],cp=chest.geometry.attributes.position;let tested=0;for(let i=0;i<cp.count;i++)if(Math.abs(cp.getZ(i))<.25&&cp.getY(i)<1.20){const p=new THREE.Vector3().fromBufferAttribute(cp,i);assert.ok(chest.applyBoneTransform(i,p.clone()).distanceTo(p)<1e-6,'belly must not follow arm weights');tested++;}assert.ok(tested>100);
   h.pose('neutral');assert.equal(h.rifle.root.visible,false);for(const m of h.parts){const p=m.geometry.attributes.position;for(let i=0;i<p.count;i++){const original=new THREE.Vector3().fromBufferAttribute(p,i);assert.ok(m.applyBoneTransform(i,original.clone()).distanceTo(original)<1e-6);}}
  }finally{h.dispose();}
 });
}
test('10k variant is reduced from the stored 30k author, preserving every garment and head component',()=>{assert.equal(reduced.sourceTriangles,author.triangles);assert.ok(reduced.triangles/author.triangles<.35);for(let i=0;i<author.parts.length;i++){assert.equal(reduced.parts[i].name,author.parts[i].name);assert.equal(reduced.parts[i].sourceTriangles,author.parts[i].triangles);}});

test('paint frame matches its four cameras and contains cap, ears and body',()=>{const f=PAINT_FRAME,camera=new THREE.OrthographicCamera(-f.width/2,f.width/2,f.height/2,-f.height/2,f.near,f.far);for(let view=0;view<4;view++){camera.position.set(f.distance*Math.cos(view*Math.PI/2),f.centerY,f.distance*Math.sin(view*Math.PI/2));camera.lookAt(0,f.centerY,0);camera.updateMatrixWorld();for(const part of author.parts)for(let i=0;i<part.position.length;i+=3){const p=part.position.slice(i,i+3),ndc=new THREE.Vector3(...p).project(camera),actual=paintCoordinates(p,view,f);assert.ok(Math.abs(ndc.x)<.99&&Math.abs(ndc.y)<.99,'uncropped surface');assert.ok(Math.abs(actual.uv[0]-(view+(ndc.x+1)/2)/4)<1e-12);assert.ok(Math.abs(actual.uv[1]-(ndc.y+1)/2)<1e-12);assert.ok(Math.abs(actual.depth-(ndc.z+1)/2)<1e-12);}}});
