import test from 'node:test';import assert from 'node:assert/strict';
import {blankMap,factoryMap,edgeKey,validateMap,parseMap,stampRoom,generateMap} from '../dist/tactics/maps.js';
import {createEditor,beginStroke,endStroke,applyBrush,replaceMap,undo,redo} from '../dist/tactics/editor-model.js';
test('a multi-tile paint stroke undoes and redoes as one operation',()=>{const e=createEditor(blankMap());beginStroke(e);for(let x=7;x<12;x++)applyBrush(e,'floor',x,8,null);endStroke(e);assert.equal(e.undo.length,1);assert.equal(e.map.terrain[8][10],'floor');undo(e);assert.equal(e.map.terrain[8][10],'yard');redo(e);assert.equal(e.map.terrain[8][10],'floor');});
test('walls and doors replace shared edges without changing terrain; erasure undoes',()=>{const e=createEditor(blankMap()),k=edgeKey('e',8,8);beginStroke(e);applyBrush(e,'wall',8,8,k);endStroke(e);assert.equal(e.map.edges[k],'wall');assert.equal(e.map.terrain[8][8],'yard');beginStroke(e);applyBrush(e,'door',8,8,k);endStroke(e);assert.equal(e.map.edges[k],'door');beginStroke(e);applyBrush(e,'erase-edge',8,8,k);endStroke(e);assert.equal(e.map.edges[k],undefined);undo(e);assert.equal(e.map.edges[k],'door');});
test('starts and travel marker are protected from crates and overlapping actors',()=>{const e=createEditor(blankMap());assert.match(applyBrush(e,'crate',3,4,null),/Move/);assert.match(applyBrush(e,'guard',3,4,null),/squad/);assert.match(applyBrush(e,'squad',3,6,null,{slot:0}),/Another/);assert.match(applyBrush(e,'crate',3,5,null),/Move/);assert.equal(e.map.starts.length,4);});
test('guards cap at 46; editing and deleting a guard preserves valid schema',()=>{const e=createEditor(generateMap());assert.match(applyBrush(e,'guard',5,5,null),/46/);const p=e.map.guards[0];applyBrush(e,'guard',p.x,p.y,null,{species:'hen',weapon:'rifle',level:p.z});assert.equal(e.map.guards.length,46);assert.equal(e.map.guards[0].species,'hen');applyBrush(e,'remove-guard',p.x,p.y,null,{level:p.z});assert.equal(e.map.guards.length,45);assert.deepEqual(validateMap(e.map),[]);});
test('room footprints fit bounds, can rotate, and create open door edges',()=>{const e=createEditor(blankMap());assert.match(applyBrush(e,'room',238,238,null,{width:6,height:5}),/fit/);assert.equal(applyBrush(e,'room',10,8,null,{width:6,height:5,rotated:true}),'');assert.equal(e.map.terrain[13][14],'floor');assert.equal(e.map.terrain[8][15],'yard');assert.ok(Object.values(e.map.edges).includes('door'));});
test('replace/import is undoable, malformed import cannot alter the working map',()=>{const e=createEditor(factoryMap()),before=JSON.stringify(e.map);assert.throws(()=>replaceMap(e,parseMap('{broken')));assert.equal(JSON.stringify(e.map),before);replaceMap(e,blankMap());assert.equal(e.map.guards.length,0);undo(e);assert.equal(e.map.guards.length,12);});
test('disconnected drafts roundtrip for repair but cannot become playable definitions',()=>{const m=blankMap();stampRoom(m,1,3,4,6);for(const k of Object.keys(m.edges))if(m.edges[k]==='door')m.edges[k]='wall';m.guards=[{x:20,y:20,species:'cow',weapon:'rifle'}];const text=JSON.stringify(m);assert.throws(()=>parseMap(text));assert.deepEqual(parseMap(text,{allowDisconnected:true}),m);assert.ok(validateMap(m).length);});

test('upper roofs create support and erased tiles and legacy crates can be restored with undo',()=>{const e=createEditor(blankMap());beginStroke(e);assert.equal(applyBrush(e,'roof-tile',10,10,null,{level:1,propKind:'roof-corrugated-flat'}),'');endStroke(e);assert.equal(e.map.upper[0]['10,10'],'floor');assert.equal(e.map.props.length,1);beginStroke(e);assert.equal(applyBrush(e,'erase-tile',10,10,null,{level:1}),'');endStroke(e);assert.equal(e.map.upper[0]['10,10'],undefined);assert.equal(e.map.props.length,0);undo(e);assert.equal(e.map.props.length,1);assert.equal(e.map.upper[0]['10,10'],'floor');applyBrush(e,'crate',20,20,null,{level:1});assert.equal(applyBrush(e,'erase-prop',20,20,null,{level:1}),'');assert.equal(e.map.upper[0]['20,20'],'floor');assert.match(applyBrush(e,'erase-tile',3,4,null),/Move/);});
