import test from 'node:test';import assert from 'node:assert/strict';import {createGame,refresh,canSee,setSneaking,movementNeighbors,setOverwatch,resolveOverwatch,equip,turnTo,emitNoise,stepInvestigation,moveGroup,stepMovement} from '../dist/tactics/engine.js';import {blankMap} from '../dist/tactics/maps.js';
function arena(){const m=blankMap();m.guards=[{x:8,y:4,z:0,species:'donkey',weapon:'pistol'}];const s=createGame(1,m),u=s.units[0],g=s.units[4];u.heading=0;g.heading=180;g.hp=500;refresh(s);return {s,u,g};}
test('overwatch reserves AP once and fires only one round without double charge',()=>{const {s,u,g}=arena();assert.ok(setOverwatch(s,u));assert.equal(u.ap,8);assert.equal(setOverwatch(s,u),false);s.phase='enemy';resolveOverwatch(s,g);assert.equal(u.ammo.assault,29);assert.equal(u.ap,8);assert.equal(u.overwatch,null);resolveOverwatch(s,g);assert.equal(u.ammo.assault,29);});
test('free weapon swap or turn cancels reserved reaction without refund',()=>{const {s,u,g}=arena();setOverwatch(s,u);assert.ok(equip(s,u,'pistol'));assert.equal(u.ap,8);s.phase='enemy';resolveOverwatch(s,g);assert.equal(u.ammo.pistol,8);s.phase='player';setOverwatch(s,u);assert.ok(turnTo(s,u,180));assert.equal(u.overwatch,null);assert.equal(u.ap,4);});
test('overwatch respects cone, walls and empty ammunition',()=>{const {s,u,g}=arena();setOverwatch(s,u);s.phase='enemy';g.x=1;resolveOverwatch(s,g);assert.ok(u.overwatch);g.x=8;s.edges['e:4:4']='wall';resolveOverwatch(s,g);assert.ok(u.overwatch);delete s.edges['e:4:4'];u.ammo.assault=0;resolveOverwatch(s,g);assert.ok(u.overwatch);});
test('stealth lowers detection distance and adds movement AP',()=>{const {s,u,g}=arena();g.x=45;assert.ok(canSee(s,g,u));setSneaking(s,u);assert.ok(!canSee(s,g,u));assert.equal(movementNeighbors(s,u).find(p=>p.x===u.x+1&&p.y===u.y).cost,4);});
test('unseen noise is approximate and investigation never reveals a target through walls',()=>{const {s,u,g}=arena();g.heading=0;g.lastKnown=null;u.x=3;u.y=4;emitNoise(s,u,10);assert.deepEqual(g.lastHeard,{x:6,y:6,z:0});assert.equal(g.lastKnown,null);s.phase='explore';g.alert=false;s.edges['e:4:4']='wall';assert.ok(stepInvestigation(s));assert.equal(g.x,7);});

test('formation orders cancel reservations and group footsteps create noise',()=>{const {s,u,g}=arena();s.units[1].x=3;s.units[1].y=6;g.heading=0;g.lastHeard=null;setOverwatch(s,u);assert.ok(moveGroup(s,[0,1],u,4,4));assert.equal(u.overwatch,null);stepMovement(s);assert.ok(g.lastHeard);});
