import test from 'node:test';
import assert from 'node:assert/strict';
import {blankMap} from '../dist/tactics/maps.js';
import {createGame,attack,previewAttack} from '../dist/tactics/engine.js';
import {PERSONALITIES,friendlyReaction,retaliationChance,helped,settleStress,personalityDescription} from '../dist/tactics/personalities.js';
function fight(){const map=blankMap();map.starts=[{x:10,y:10},{x:11,y:10},{x:3,y:3},{x:3,y:5}];map.guards=[{x:16,y:10,species:'pig-foreman',weapon:'pistol'}];const s=createGame(1,map),[a,b]=s.units;s.socialSeed=1;for(const u of [a,b]){u.weapon='pistol';u.ammo.pistol=2;u.hp=u.maxHp=1000;u.accuracy=1000;u.social.stress=100;const other=u===a?b:a;u.social.bonds[other.name]=-100;u.social.incidents[other.name]={hits:8,damage:100,grudge:100};}a.heading=0;a.ap=4;b.ap=0;return {s,a,b,target:s.units[4]};}
test('mercs have separate authored voices, relationships and persistent personal memories',()=>{const {s,a,b}=fight();assert.equal(Object.keys(PERSONALITIES).length,4);assert.notDeepEqual(a.social.bonds,b.social.bonds);const seed=s.seed;const response=friendlyReaction(s,b,a,20,false);assert.equal(response.retaliate,false);assert.equal(s.seed,seed);assert.match(personalityDescription(b).join(' '),/courier/);assert.match(b.social.memories[0],/Yakov/);assert.deepEqual(structuredClone(b).social,b.social);});
test('landed replies form a finite chain, spend loaded rounds and no AP, and do not reload',()=>{const {s,a,b,target}=fight();assert.equal(attack(s,a,target),true);assert.equal(s.effect.sequence.length,4);assert.equal(s.effect.sequence.filter(e=>e.reply).length,3);assert.equal(a.ammo.pistol,0);assert.equal(b.ammo.pistol,0);assert.equal(a.ap,0);assert.equal(b.ap,0);assert.equal(a.hp,946);assert.equal(b.hp,946);assert.equal(target.hp,45);assert.equal(previewAttack(s,a,b).ok,false);assert.equal(attack(s,a,b),false);});
test('an unarmed or empty recipient quips and cannot get a free weapon switch',()=>{for(const weapon of ['hands','pistol']){const {s,a,b,target}=fight();b.weapon=weapon;b.ammo.pistol=0;attack(s,a,target);assert.equal(s.effect.sequence.length,1);assert.equal(b.weapon,weapon);assert.ok(s.effect.sequence[0].dialogue);}});
test('retaliation interrupts a burst and stops its remaining rounds if the shooter falls',()=>{const {s,a,b,target}=fight();a.weapon='assault';a.ap=6;a.hp=20;const ammo=a.ammo.assault;attack(s,a,target,true);assert.equal(a.hp,0);assert.equal(a.ammo.assault,ammo-1);assert.equal(b.ammo.pistol,1);assert.equal(s.effect.sequence.length,2);});
test('incapacitated recipients cannot reply',()=>{const {s,a,b,target}=fight();b.hp=10;attack(s,a,target);assert.equal(s.effect.sequence.length,1);assert.equal(b.hp,0);assert.equal(b.ammo.pistol,2);});
test('burning recipients cannot retaliate and missed replies do not cause another reaction',()=>{const {s,a,b,target}=fight();b.burningTurns=3;attack(s,a,target);assert.equal(s.effect.sequence.length,1);assert.equal(b.ammo.pistol,2);let found=false;for(let seed=1;seed<50&&!found;seed++){const f=fight();f.s.seed=seed;f.b.accuracy=-1000;attack(f.s,f.a,f.target);if(f.s.effect.sequence.length===2&&!f.s.effect.sequence[1].hit){found=true;assert.equal(f.a.ammo.pistol,1);assert.equal(f.b.ammo.pistol,1);assert.equal(f.a.social.incidents[f.b.name].hits,8);}}assert.ok(found);});
test('history and distrust increase retaliation; medical help rebuilds trust; rest preserves grudges',()=>{const {s,a,b}=fight();b.social.stress=0;b.social.bonds[a.name]=40;b.social.incidents={};const calm=retaliationChance(b,a,10);friendlyReaction(s,b,a,30,false);friendlyReaction(s,b,a,30,false);assert.ok(retaliationChance(b,a,10)>calm);const bond=b.social.bonds[a.name],grudge=b.social.incidents[a.name].grudge;assert.ok(helped(b,a));assert.ok(b.social.bonds[a.name]>bond);settleStress(b,100);assert.equal(b.social.stress,0);assert.equal(b.social.incidents[a.name].grudge,grudge);});
