import test from 'node:test';import assert from 'node:assert/strict';
import {blankMap,addStairs} from '../dist/tactics/maps.js';
import {createGame,setStance,stanceOf,pathTo,pathCost,move,stepMovement,stepEnemy,endTurn,movementNeighbors} from '../dist/tactics/engine.js';
import {createWorld,travel,currentMap} from '../dist/tactics/world.js';
function arena(){const m=blankMap();m.guards=[{x:220,y:220,z:0,species:'cow',weapon:'knife'}];const s=createGame(1,m);s.phase='player';s.units[4].alert=true;return s;}
test('all six direct stance transitions cost exactly2AP; repeat/invalid/insufficient changes do nothing',()=>{for(const from of ['standing','kneeling','prone'])for(const to of ['standing','kneeling','prone']){const s=arena(),u=s.units[0];u.stance=from;assert.equal(setStance(s,u,to),from!==to);assert.equal(u.ap,from===to?12:10);assert.equal(u.stance,to);}const s=arena(),u=s.units[0];u.ap=1;assert.equal(setStance(s,u,'prone'),false);u.ap=12;assert.equal(setStance(s,u,'toString'),false);assert.equal(u.ap,12);assert.equal(stanceOf(u),'standing');});
test('standing kneeling and prone routes debit2/4/8AP per tile and reject over-budget routes',()=>{for(const [stance,cost]of [['standing',2],['kneeling',4],['prone',8]]){const s=arena(),u=s.units[0];u.stance=stance;assert.equal(pathCost(pathTo(s,u,5,4)),cost*2);u.ap=cost-1;assert.equal(move(s,u,4,4),false);u.ap=cost;assert.ok(move(s,u,4,4));assert.ok(stepMovement(s));assert.equal(u.ap,0);assert.equal(u.x,4);}});
test('movement locks stance changes and rechecks live stance cost before a queued step',()=>{const s=arena(),u=s.units[0];assert.ok(move(s,u,5,4));assert.equal(setStance(s,u,'prone'),false);u.stance='prone';u.ap=7;assert.equal(stepMovement(s),false);assert.equal(u.x,3);assert.equal(u.ap,7);assert.equal(s.queue.length,0);});
test('stance controls reject enemy turns and fallen characters; exploration stays free',()=>{const s=arena(),u=s.units[0];s.phase='enemy';assert.equal(setStance(s,u,'kneeling'),false);s.phase='player';u.hp=0;assert.equal(setStance(s,u,'kneeling'),false);u.hp=100;s.phase='explore';s.units[4].alert=false;u.ap=0;assert.ok(setStance(s,u,'prone'));assert.equal(u.ap,0);assert.ok(move(s,u,4,4));stepMovement(s);assert.equal(u.x,4);assert.equal(u.stance,'prone');});
test('climbing requires standing and preserves the established vertical AP cost',()=>{const m=blankMap();addStairs(m,3,4,0,'ladder');const s=createGame(1,m),u=s.units[0];u.stance='prone';assert.equal(pathTo(s,u,3,4,1),null);assert.equal(movementNeighbors(s,u).some(p=>p.z===1),false);assert.ok(setStance(s,u,'standing'));assert.equal(pathCost(pathTo(s,u,3,4,1)),3);});
test('enemy standing movement spends2AP per tile',()=>{const s=arena(),g=s.units[4];for(const u of s.units.slice(1,4))u.hp=0;Object.assign(g,{x:10,y:4,ap:7,lastKnown:{x:3,y:4,z:0}});s.phase='enemy';s.enemyIndex=4;assert.ok(stepEnemy(s));assert.equal(g.ap,5);assert.equal(g.x,9);});
test('stance survives AP refresh and local-map travel',()=>{const world=createWorld(blankMap()),s=currentMap(world),u=s.units[0];assert.ok(setStance(s,u,'kneeling'));s.units[3].y=5;world.definitions.yard=blankMap('Yard');assert.ok(travel(world,'yard').ok);assert.equal(currentMap(world).units[0].stance,'kneeling');const combat=arena();combat.units[0].stance='prone';assert.ok(endTurn(combat));combat.enemyIndex=combat.units.length;stepEnemy(combat);assert.equal(combat.units[0].stance,'prone');assert.equal(combat.units[0].ap,12);});
