import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,W,H,WEAPONS,squad,guards,move,stepMovement,refresh,pathTo,lineOfSight,previewAttack,attack,equip,reload,endTurn,stepEnemy,coverAgainst} from '../dist/tactics/engine.js';
function arena(){const s=createGame();s.edges={};s.map=Array.from({length:H},()=>Array(W).fill('yard'));s.units.forEach((u,i)=>{u.x=24;u.y=i+2;u.alert=false;});s.units.slice(1,4).forEach((u,i)=>{u.x=2;u.y=4+i;});const a=s.units[0],b=s.units[4];a.x=3;a.y=3;b.x=5;b.y=3;s.phase='player';refresh(s);return {s,a,b};}
test('exact cast, player advantage, legal spawn and long-range initial contact',()=>{const s=createGame();assert.equal(squad(s).length,4);assert.equal(guards(s).length,12);assert.equal(s.phase,'player');assert.equal(new Set(s.units.map(u=>`${u.x},${u.y}`)).size,16);for(const u of s.units)assert.ok(['yard','floor','door'].includes(s.map[u.y][u.x]));assert.ok(s.units[0].hp>s.units[4].hp);assert.ok(s.units[0].ap>s.units[4].ap);});
test('all guards are reachable through factory doors',()=>{const s=createGame(),u=s.units[0];for(const g of guards(s)){assert.ok([[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>pathTo(s,u,g.x+dx,g.y+dy)));}});
test('BFS avoids occupied tiles and solid cover; invalid moves never spend AP',()=>{const {s,a,b}=arena();s.map[3][4]='crate';const p=pathTo(s,a,6,3);assert.ok(p.length>3);assert.ok(!p.some(p=>p.x===b.x&&p.y===b.y));assert.equal(move(s,a,b.x,b.y),false);assert.equal(a.ap,12);assert.equal(move(s,a,4,3),false);a.ap=1;assert.equal(move(s,a,6,3),false);});
test('movement consumes actual path AP and does not overlap',()=>{const {s,a}=arena();assert.ok(move(s,a,3,6));while(s.queue.length)stepMovement(s);assert.equal(a.ap,6);assert.equal(a.y,6);});
test('walls and diagonal corners block sight, crates provide directional cover',()=>{const {s,a,b}=arena();s.map[3][4]='wall';assert.equal(lineOfSight(s,a,b),false);s.map[3][4]='crate';assert.equal(lineOfSight(s,a,b),true);assert.equal(coverAgainst(s,a,b),true);a.x=7;assert.equal(coverAgainst(s,a,b),false);s.map[3][4]='wall';assert.equal(lineOfSight(s,{x:3,y:3},{x:4,y:4}),false);});
test('fog hides guard behind wall and remembers explored terrain',()=>{const s=createGame();assert.ok(!s.visible.has('12,6'));const seen=s.seen.size;s.units[0].x=8;s.units[0].y=11;refresh(s);assert.ok(s.seen.size>=seen);});
test('contact interrupts real-time path; LOS break cannot reset AP',()=>{const {s,a,b}=arena();s.units.slice(1,4).forEach(u=>u.hp=0);s.units.slice(5).forEach(u=>u.hp=0);s.phase='explore';b.alert=false;b.x=64;a.x=3;refresh(s);assert.equal(s.phase,'explore');move(s,a,8,3);stepMovement(s);assert.equal(s.phase,'player');assert.equal(s.queue.length,0);a.ap=2;s.map[3][8]='wall';refresh(s);assert.equal(s.phase,'player');assert.equal(a.ap,2);});
test('weapon identities, range, ammo persistence, equip and reload costs',()=>{const {s,a,b}=arena();assert.equal(Object.keys(WEAPONS).length,5);equip(s,a,'hands');assert.equal(previewAttack(s,a,b).reason,'Out of range');a.ap=12;equip(s,a,'pistol');attack(s,a,b);assert.equal(a.ammo.pistol,7);a.ap=12;assert.equal(equip(s,a,'rifle'),false);equip(s,a,'assault');equip(s,a,'pistol');assert.equal(a.ammo.pistol,7);assert.equal(a.ap,12);reload(s,a);assert.equal(a.ap,9);assert.equal(a.ammo.pistol,8);});
test('burst uses three rounds and 6 AP, rejects undersized magazine',()=>{const {s,a,b}=arena();a.ammo.assault=2;assert.equal(attack(s,a,b,true),false);assert.equal(a.ap,12);a.ammo.assault=30;assert.ok(attack(s,a,b,true));assert.equal(a.ap,6);assert.equal(a.ammo.assault,27);});
test('exploration opening attack enters combat and spends AP',()=>{const {s,a,b}=arena();s.phase='explore';b.alert=false;assert.ok(attack(s,a,b));assert.equal(s.phase,'player');assert.equal(a.ap,8);});
test('enemy phase locks player controls, terminates, and applies damage',()=>{const {s,a,b}=arena();b.weapon='pistol';assert.ok(endTurn(s));assert.equal(move(s,a,4,4),false);assert.equal(equip(s,a,'rifle'),false);assert.equal(attack(s,a,b),false);let n=0;while(s.phase==='enemy'&&n++<300)stepEnemy(s);assert.ok(n<300);assert.equal(s.phase,'player');assert.equal(a.ap,12);assert.ok(s.log.some(x=>x.includes('Boris → Yakov')));});
test('cleared encounters resume exploration; cleared maps allow movement and loss locks input',()=>{let {s,a,b}=arena();guards(s).forEach(g=>{g.alert=false;g.x=220;});b.alert=true;b.hp=0;refresh(s);assert.equal(s.phase,'explore');guards(s).forEach(g=>g.hp=0);refresh(s);assert.equal(s.phase,'won');assert.equal(move(s,a,4,4),true);s=createGame();squad(s).forEach(u=>u.hp=0);refresh(s);assert.equal(s.phase,'lost');assert.equal(endTurn(s),false);});
test('same seed produces repeatable shots',()=>{const run=()=>{const {s,a,b}=arena();attack(s,a,b,true);return [s.seed,b.hp];};assert.deepEqual(run(),run());});

test('guard holds firing position when remaining AP cannot pay for another shot',()=>{const {s,a,b}=arena();b.weapon='pistol';b.ap=2;s.phase='enemy';s.enemyIndex=b.id;const before=[b.x,b.y];stepEnemy(s);assert.deepEqual([b.x,b.y],before);assert.equal(b.ap,0);});
