import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,moveGroup,stepMovement,previewAttack,attack,refresh} from '../dist/tactics/engine.js';import {blankMap} from '../dist/tactics/maps.js';
function group(){return createGame(1,blankMap());}
test('four characters advance in a single tick and retain offsets at destination',()=>{const s=group(),start=s.units.map(u=>({x:u.x,y:u.y}));assert.equal(moveGroup(s,[0,1,2,3],s.units[0],13,4),true);assert.equal(stepMovement(s),true);assert.ok(s.units.every((u,i)=>u.x!==start[i].x||u.y!==start[i].y));for(let i=0;i<30&&s.queue.length;i++)stepMovement(s);assert.equal(s.queue.length,0);s.units.forEach((u,i)=>assert.deepEqual({x:u.x,y:u.y},{x:start[i].x+10,y:start[i].y}));assert.equal(new Set(s.units.map(u=>u.x+','+u.y)).size,4);});
test('group stop cancels every route and combat spends each members movement AP',()=>{const m=blankMap();m.guards=[{x:220,y:220,z:0,species:'pig-foreman',weapon:'pistol'}];const s=createGame(1,m,false);s.phase='player';s.units[4].alert=true;s.units.slice(0,4).forEach(u=>u.ap=2);assert.equal(moveGroup(s,[0,1,2,3],s.units[0],13,4),true);stepMovement(s);assert.ok(s.units.slice(0,4).every(u=>u.ap===0));stepMovement(s);assert.equal(s.queue.length,0);const positions=s.units.map(u=>[u.x,u.y]);stepMovement(s);assert.deepEqual(s.units.map(u=>[u.x,u.y]),positions);});
test('blocked formation slots use distinct nearby destinations without overlaps',()=>{const s=group();s.map[4][13]='crate';refresh(s);assert.equal(moveGroup(s,[0,1,2,3],s.units[0],13,4),true);const goals=s.queue[0].group.map(o=>o.goal.x+','+o.goal.y);assert.equal(new Set(goals).size,4);for(let i=0;i<40&&s.queue.length;i++){stepMovement(s);assert.equal(new Set(s.units.map(u=>u.x+','+u.y)).size,4);}assert.equal(s.queue.length,0);});
test('aimed torso retains existing shot while head trades accuracy for damage',()=>{const m=blankMap();m.guards=[{x:5,y:4,z:0,species:'pig-foreman',weapon:'pistol'}];const s=createGame(1,m),u=s.units[0],g=s.units[4],normal=previewAttack(s,u,g),torso=previewAttack(s,u,g,false,'torso'),head=previewAttack(s,u,g,false,'head');assert.deepEqual(normal,torso);assert.equal(head.chance,torso.chance-25);assert.equal(head.damage,Math.round(torso.damage*1.5));u.ap=0;const ammo=u.ammo.assault;assert.equal(attack(s,u,g,false,false,'head'),false);assert.equal(u.ammo.assault,ammo);assert.equal(previewAttack(s,u,g,false,'unknown').ok,false);});

test('one-tile formation movement uses teammates vacated cells',()=>{const s=group();s.units.forEach((u,i)=>{u.x=10+i;u.y=10;});refresh(s);assert.equal(moveGroup(s,[0,1,2,3],s.units[0],11,10),true);stepMovement(s);assert.equal(s.queue.length,0);assert.deepEqual(s.units.map(u=>[u.x,u.y]),[[11,10],[12,10],[13,10],[14,10]]);});
