import test from 'node:test';import assert from 'node:assert/strict';
import {blankMap,setTerrain,neighbors,validateMap,parseMap,edgeKey} from '../dist/tactics/maps.js';
import {createEditor,applyBrush,beginStroke,endStroke,undo,redo} from '../dist/tactics/editor-model.js';
import {createGame,pathTo,pathCost,move,stepMovement,previewAttack,lineOfSight,stepEnemy} from '../dist/tactics/engine.js';
function fixture(){const m=blankMap();setTerrain(m,4,4,1,'floor');m.climbs=[{x:3,y:4,z:0,dx:1,dy:0}];return m;}
test('marked roof climbs traverse exactly one adjacent level for6AP in either direction',()=>{const m=fixture();assert.deepEqual(validateMap(m),[]);const s=createGame(1,m),u=s.units[0];assert.equal(pathCost(pathTo(s,u,4,4,1)),6);s.phase='player';u.ap=5;assert.equal(move(s,u,4,4,1),false);u.ap=12;assert.ok(move(s,u,4,4,1));stepMovement(s);assert.deepEqual([u.x,u.y,u.z,u.ap],[4,4,1,6]);assert.equal(neighbors(s,u).find(p=>p.kind==='roof').cost,6);assert.equal(pathTo(s,u,4,4,2),null);assert.equal(lineOfSight(s,{x:4,y:4,z:0},{x:4,y:4,z:1}),false);});
test('roof geometry rejects missing support, blocked upper edge, blocked headroom and multi-level records',()=>{for(const mutate of [m=>setTerrain(m,4,4,1,'void'),m=>setTerrain(m,3,4,1,'floor'),m=>m.edges[edgeKey('e',3,4,1)]='wall',m=>m.climbs[0].dx=2,m=>m.climbs[0].z=2]){const m=fixture();mutate(m);assert.ok(validateMap(m).length);}const m=fixture();delete m.climbs;assert.deepEqual(validateMap(m),[]);assert.equal(neighbors(m,{x:3,y:4,z:0}).some(p=>p.z===1),false);});
test('roof editor creation, endpoint protection, roundtrip and erase undo remain consistent',()=>{const e=createEditor(blankMap());setTerrain(e.map,4,4,1,'floor');beginStroke(e);assert.equal(applyBrush(e,'roof',3,4,edgeKey('e',3,4)), '');endStroke(e);assert.equal(neighbors(e.map,{x:3,y:4,z:0}).find(p=>p.kind==='roof').cost,6);assert.ok(applyBrush(e,'void',4,4,null,{level:1}));assert.ok(applyBrush(e,'prop',4,4,null,{level:1,propKind:'crate-wood'}));assert.deepEqual(parseMap(JSON.stringify(e.map)).climbs,e.map.climbs);beginStroke(e);applyBrush(e,'erase-roof',4,4,null,{level:1});endStroke(e);assert.equal(neighbors(e.map,{x:3,y:4,z:0}).some(p=>p.kind==='roof'),false);undo(e);assert.equal(e.map.climbs.length,1);redo(e);assert.equal(e.map.climbs.length,0);});
test('queued climb stops if its upper edge is blocked before execution',()=>{const s=createGame(1,fixture()),u=s.units[0];s.phase='player';assert.ok(move(s,u,4,4,1));s.edges[edgeKey('e',3,4,1)]='wall';assert.equal(stepMovement(s),false);assert.equal(u.z,0);assert.equal(u.ap,12);});
test('two-level uphill range costs2tiles, downhill has no vertical distance tax, melee unchanged',()=>{const m=blankMap();setTerrain(m,5,5,2,'floor');const s=createGame(1,m),a=s.units[0],b=s.units[1];Object.assign(a,{x:5,y:5,z:2,weapon:'pistol'});Object.assign(b,{x:13,y:5,z:0,weapon:'pistol',team:'guard'});s.visible.add('13,5');let p=previewAttack(s,a,b);assert.equal(p.range,8);assert.equal(p.rangePenalty,0);assert.ok(p.ok);p=previewAttack(s,b,a);assert.equal(p.rangePenalty,2);assert.equal(p.range,6);assert.equal(p.ok,false);a.weapon='knife';assert.equal(previewAttack(s,a,b).rangePenalty,0);});

test('guards can afford a roof-only pursuit route within their7AP turn',()=>{const m=fixture();m.guards=[{x:3,y:3,z:0,species:'donkey',weapon:'knife'}];const s=createGame(1,m),g=s.units[4];assert.equal(g.maxAp,7);assert.equal(pathTo(s,g,4,4,1),null);s.units[0].x=2;s.units[0].y=4;assert.equal(pathCost(pathTo(s,g,4,4,1)),7);});

test('enemy AI spends6AP to climb toward a remembered rooftop target',()=>{const m=fixture();setTerrain(m,5,4,1,'floor');m.starts[0]={x:5,y:4,z:1};m.guards=[{x:3,y:4,z:0,species:'donkey',weapon:'knife'}];const s=createGame(1,m),g=s.units[4];for(const u of s.units.slice(1,4))u.hp=0;s.phase='enemy';s.enemyIndex=4;g.alert=true;g.lastKnown={x:5,y:4,z:1};assert.ok(stepEnemy(s));assert.deepEqual([g.x,g.y,g.z,g.ap],[4,4,1,1]);});
