import test from 'node:test';import assert from 'node:assert/strict';
import {blankMap,validateMap,edgeKey,parseMap} from '../dist/tactics/maps.js';
import {createEditor,applyBrush,beginStroke,endStroke,undo,redo} from '../dist/tactics/editor-model.js';
import {propAt} from '../dist/tactics/environment.js';
test('prop placement checks whole footprint and cached lookups follow placement/erase/undo',()=>{const e=createEditor(blankMap());assert.equal(propAt(e.map,8,8),undefined);beginStroke(e);assert.equal(applyBrush(e,'prop',8,8,null,{propKind:'table-wood'}),'');endStroke(e);assert.equal(propAt(e.map,9,8).kind,'table-wood');assert.match(applyBrush(e,'prop',9,8,null,{propKind:'crate-wood'}),/footprint/);assert.match(applyBrush(e,'void',9,8,null),/Move/);beginStroke(e);applyBrush(e,'erase-prop',9,8,null);endStroke(e);assert.equal(propAt(e.map,8,8),undefined);undo(e);assert.equal(propAt(e.map,9,8).kind,'table-wood');redo(e);assert.equal(propAt(e.map,9,8),undefined);});
test('rotated props fit 1x2 and reject walls, unsupported floors and protected starts',()=>{const e=createEditor(blankMap());assert.match(applyBrush(e,'prop',2,4,null,{propKind:'table-wood'}),/Move/);assert.match(applyBrush(e,'prop',239,10,null,{propKind:'table-wood'}),/footprint/);assert.equal(applyBrush(e,'prop',239,10,null,{propKind:'table-wood',rotated:true}),'');assert.match(applyBrush(e,'prop',8,8,null,{propKind:'crate-stack',level:1}),/footprint/);e.map.edges[edgeKey('e',8,8)]='wall';assert.match(applyBrush(e,'prop',8,8,null,{propKind:'table-wood'}),/straddle/);assert.deepEqual(validateMap(e.map),[]);});
test('all new brush data survives a portable JSON roundtrip',()=>{const e=createEditor(blankMap());applyBrush(e,'texture',9,9,null,{groundKind:'ground-gravel'});applyBrush(e,'prop',9,9,null,{propKind:'barrel-single'});applyBrush(e,'wall',9,9,edgeKey('e',9,9),{edgeKind:'fence-chainlink'});applyBrush(e,'ladder',10,10,null,{level:0});assert.deepEqual(parseMap(JSON.stringify(e.map)),e.map);assert.equal(e.map.stairs[0].kind,'ladder');assert.equal(e.map.edges[edgeKey('e',9,9)],'fence-chainlink');});

test('later wall edits cannot bisect a two-cell prop',()=>{const e=createEditor(blankMap());applyBrush(e,'prop',8,8,null,{propKind:'table-wood'});applyBrush(e,'wall',8,8,edgeKey('e',8,8),{});assert.ok(validateMap(e.map).some(e=>e.includes('footprint crosses')));});
