import test from 'node:test';import assert from 'node:assert/strict';
import {blankMap,neighbors,edgeKey,setTerrain} from '../dist/tactics/maps.js';
import {createGame,movementNeighbors,pathTo,pathCost,move,stepMovement,stepEnemy} from '../dist/tactics/engine.js';
function arena(){const s=createGame(1,blankMap());s.phase='player';return s;}
test('all four diagonals use3/6/12AP for standing kneeling prone',()=>{for(const [stance,cost]of [['standing',3],['kneeling',6],['prone',12]])for(const dx of [-1,1])for(const dy of [-1,1]){const s=arena(),u=s.units[0];Object.assign(u,{x:10,y:10,stance});assert.equal(pathCost(pathTo(s,u,10+dx,10+dy)),cost);u.ap=cost-1;assert.equal(move(s,u,10+dx,10+dy),false);u.ap=cost;assert.ok(move(s,u,10+dx,10+dy));assert.ok(stepMovement(s));assert.equal(u.ap,0);assert.deepEqual([u.x,u.y],[10+dx,10+dy]);}});
test('every corner edge and either obstructed flank blocks a diagonal in both directions',()=>{for(const k of [edgeKey('e',10,10),edgeKey('s',10,10),edgeKey('s',11,10),edgeKey('e',10,11)]){const m=blankMap();m.edges[k]='wall';for(const [p,q]of [[{x:10,y:10},{x:11,y:11}],[{x:11,y:11},{x:10,y:10}]])assert.equal(neighbors(m,p).some(v=>v.x===q.x&&v.y===q.y),false);}for(const kind of ['crate','water','void'])for(const [x,y]of [[11,10],[10,11]]){const m=blankMap();m.terrain[y][x]=kind;assert.equal(neighbors(m,{x:10,y:10}).some(p=>p.x===11&&p.y===11),false);}});
test('living flank occupants block diagonals and queued movement rechecks late blockers',()=>{const s=arena(),u=s.units[0],other=s.units[1];Object.assign(u,{x:10,y:10});assert.ok(move(s,u,11,11));Object.assign(other,{x:11,y:10});assert.equal(movementNeighbors(s,u).some(p=>p.x===11&&p.y===11),false);assert.equal(stepMovement(s),false);assert.equal(u.ap,12);other.hp=0;assert.equal(movementNeighbors(s,u).find(p=>p.x===11&&p.y===11).cost,3);});
test('diagonal upper movement needs support in both flank tiles and destination',()=>{const m=blankMap();for(const [x,y]of [[10,10],[11,10],[10,11],[11,11]])setTerrain(m,x,y,1,'floor');assert.equal(neighbors(m,{x:10,y:10,z:1}).find(p=>p.x===11&&p.y===11).cost,1.5);setTerrain(m,11,10,1,'void');assert.equal(neighbors(m,{x:10,y:10,z:1}).some(p=>p.x===11&&p.y===11),false);});
test('mixed cardinal and diagonal path uses optimal octile distance',()=>{const s=arena(),u=s.units[0];Object.assign(u,{x:10,y:10});assert.equal(pathCost(pathTo(s,u,14,12)),10);});
test('melee guard closes to cardinal striking distance rather than stopping diagonally',()=>{const m=blankMap();m.starts[0]={x:10,y:10,z:0};m.guards=[{x:12,y:12,z:0,species:'donkey',weapon:'knife'}];const s=createGame(1,m),g=s.units[4];for(const u of s.units.slice(1,4))u.hp=0;s.phase='enemy';s.enemyIndex=4;g.alert=true;g.lastKnown={x:10,y:10,z:0};for(let i=0;i<3&&Math.abs(g.x-10)+Math.abs(g.y-10)>1;i++)stepEnemy(s);assert.equal(Math.abs(g.x-10)+Math.abs(g.y-10),1);});
