import test from 'node:test';import assert from 'node:assert/strict';
import {blankMap,setTerrain,addStairs,edgeKey,validateMap} from '../dist/tactics/maps.js';
import {blockCanvas,extractBlock,validateBlock,openBlock,placeBlock} from '../dist/tactics/blocks.js';
import {createEditor,replaceMap,undo} from '../dist/tactics/editor-model.js';
function design(){const m=blockCanvas('Workshop block');setTerrain(m,4,4,1,'floor');m.climbs=[{x:3,y:4,z:0,dx:1,dy:0}];addStairs(m,8,8,0,'ladder');m.props=[{x:10,y:10,z:0,kind:'workbench-metal'}];m.edges[edgeKey('e',-1,7)]='wall';m.edges[edgeKey('s',8,23,1)]='fence-railing';m.guards=[{x:12,y:12,z:0,species:'cow',weapon:'pistol'}];return extractBlock(m);}
test('block JSON roundtrip preserves all three levels and terrain geometry without squad markers',()=>{const d=design();assert.equal(d.terrain.length,24);assert.equal(d.terrain[0].length,24);assert.equal(d.starts,undefined);assert.deepEqual(extractBlock(openBlock(JSON.parse(JSON.stringify(d)))),d);assert.equal(validateBlock(d),d);});
test('place block into sector10,10 transforms edges and climbs and is undoable',()=>{const e=createEditor(blankMap()),d=design(),next=placeBlock(e.map,d,9,9);assert.equal(next.props[0].x,226);assert.equal(next.edges[edgeKey('e',215,223)],'wall');assert.equal(next.climbs[0].x,219);assert.equal(next.guards[0].x,228);assert.deepEqual(validateMap(next),[]);replaceMap(e,next);undo(e);assert.equal(e.map.props.length,0);});
test('block placement rejects obstructed squad starts atomically',()=>{const m=blankMap(),d=design();d.terrain[4][3]='water';const before=JSON.stringify(m);assert.throws(()=>placeBlock(m,d,0,0));assert.equal(JSON.stringify(m),before);});
test('sector capture rejects crossing props and roof links',()=>{const m=blockCanvas();m.props=[{x:23,y:5,z:0,kind:'table-wood'}];assert.throws(()=>extractBlock(m),/boundary/);m.props=[];m.climbs=[{x:23,y:4,z:0,dx:1,dy:0}];assert.throws(()=>extractBlock(m),/boundary/);});
test('block import rejects malformed bounds and unknown content',()=>{for(const mutate of [d=>d.terrain[0].pop(),d=>d.props[0].x=24,d=>d.edges['e:24:5']='wall',d=>d.upper[0]['24,4']='floor',d=>d.climbs[0].dx=25,d=>d.props[0].kind='unknown',d=>d.guards[0].species='unknown']){const d=design();mutate(d);assert.throws(()=>validateBlock(d));}});
test('replacing a sector removes old content on all levels but keeps neighboring designs',()=>{let m=placeBlock(blankMap(),design(),1,1);m=placeBlock(m,design(),2,2);m=placeBlock(m,extractBlock(blockCanvas('Empty')),1,1);assert.equal(m.props.length,1);assert.equal(m.props[0].x,58);assert.equal(m.climbs.length,1);assert.equal(m.guards.length,1);assert.equal(m.upper[0]['28,28'],undefined);});

test('block import rejects falsy floor values and aliased edges',()=>{const a=design();a.upper[0]['1,1']='';assert.throws(()=>validateBlock(a));const b=design();b.edges['e:01:1']='wall';assert.throws(()=>validateBlock(b));});
