import test from 'node:test';import assert from 'node:assert/strict';
import {blankMap,generateMap,validateMap,addStairs,edgeKey,neighbors,setTerrain,parseMap} from '../dist/tactics/maps.js';
import {generateSectorPlan,validateSectorPlan} from '../dist/tactics/sector-rules.js';
import {createGame,lineOfSight,pathTo,pathCost,previewAttack,coverAgainst,refresh,canSee,move,stepMovement} from '../dist/tactics/engine.js';
import {propCells} from '../dist/tactics/environment.js';
test('ladders cost3AP, stairs2AP and old connections remain stairs',()=>{const m=blankMap();addStairs(m,3,4,0,'ladder');addStairs(m,3,4,1);const s=createGame(1,m);assert.equal(pathCost(pathTo(s,s.units[0],3,4,2)),5);assert.equal(neighbors(s,{x:3,y:4,z:1}).find(p=>p.z===0).cost,3);delete m.stairs[0].kind;assert.equal(neighbors(m,{x:3,y:4,z:0}).find(p=>p.z===1).cost,2);});
test('fences block crossing but not sight or cover, walls block both',()=>{const m=blankMap();m.edges[edgeKey('e',3,4)]='fence-chainlink';const s=createGame(1,m),a={x:3,y:4,z:0},b={x:4,y:4,z:0};assert.ok(lineOfSight(s,a,b));assert.ok(pathTo(s,s.units[0],4,4).length>1);assert.equal(coverAgainst(s,b,a),false);s.edges[edgeKey('e',3,4)]='wall-brick';assert.equal(lineOfSight(s,a,b),false);});
test('two-tile props occupy both cells, tall crates occlude and pallets stay walkable',()=>{const m=blankMap();m.props=[{x:4,y:4,z:0,kind:'table-wood'},{x:6,y:6,z:0,kind:'crate-stack'},{x:4,y:7,z:0,kind:'pallet'}];const s=createGame(1,m);assert.equal(pathTo(s,s.units[0],5,4),null);assert.ok(pathTo(s,s.units[0],4,7));assert.equal(lineOfSight(s,{x:5,y:6,z:0},{x:7,y:6,z:0}),false);assert.deepEqual(propCells({x:8,y:8,z:1,kind:'table-wood',rotated:true}),[{x:8,y:8,z:1},{x:8,y:9,z:1}]);assert.ok(coverAgainst(s,{x:2,y:4,z:0},{x:6,y:4,z:0}));});
test('height adds modest ranged reach and uphill cover without overriding solid floors',()=>{const m=blankMap();setTerrain(m,5,5,1,'floor');const s=createGame(1,m),a=s.units[0],b=s.units[1];Object.assign(a,{x:5,y:5,z:1,weapon:'pistol'});Object.assign(b,{x:13,y:5,z:0,team:'guard'});s.phase='player';s.visible.add('13,5');const p=previewAttack(s,a,b);assert.equal(p.range,9);assert.equal(p.rangeBonus,1);assert.ok(p.ok);const reverse=previewAttack(s,b,a);assert.equal(reverse.heightCover,true);assert.equal(reverse.coverPenalty,15);a.weapon='knife';assert.equal(previewAttack(s,a,b).rangeBonus,0);b.x=5;assert.equal(lineOfSight(s,a,b),false);});
test('seeded river sectors match sockets and make exactly two bridges in either orientation',()=>{for(const orientation of ['ns','ew'])for(const seed of [1,7,83]){const p=generateSectorPlan(seed,orientation);assert.deepEqual(validateSectorPlan(p),[]);assert.equal(p.cells.flat().filter(t=>t==='bridge-ns').length,2);const m=generateMap(seed,'River',46,{layout:'river',orientation});assert.deepEqual(validateMap(m),[]);assert.deepEqual(parseMap(JSON.stringify(m)),m);const s=createGame(1,m);assert.ok(pathTo(s,s.units[0],239,239));const bridges=m.terrain.flat().filter(t=>t==='bridge');assert.equal(bridges.length,48);}});
test('river rules reject a missing bridge deck, blocked road or incompatible sector',()=>{const m=generateMap(7,'River',0,{layout:'river'}),p=m.sectors;const row=p.cells.findIndex(r=>r.includes('bridge-ns')),col=p.cells[row].indexOf('bridge-ns');m.terrain[row*24+10][col*24+9]='water';assert.ok(validateMap(m).some(e=>e.includes('River rule')));p.cells[row][col]='river-ns';assert.ok(validateSectorPlan(p).length);});

test('queued vertical movement uses the current ladder AP cost',()=>{const m=blankMap();addStairs(m,3,4,0);m.guards=[{x:220,y:220,z:0,species:'cow',weapon:'pistol'}];const s=createGame(1,m),u=s.units[0];s.units[4].alert=true;s.phase='player';u.ap=2;assert.ok(move(s,u,3,4,1));s.stairs[0].kind='ladder';assert.equal(stepMovement(s),false);assert.equal(u.ap,2);assert.equal(u.z,0);});

test('spotting downhill starts combat even when the guard cannot see back',()=>{const m=blankMap();addStairs(m,3,4,0);m.starts[0].z=1;m.guards=[{x:12,y:4,z:0,species:'cow',weapon:'pistol'}];const s=createGame(1,m),a=s.units[0],b=s.units[4];assert.ok(canSee(s,a,b));assert.equal(canSee(s,b,a),false);assert.equal(s.phase,'player');assert.equal(b.lastKnown,null);});

test('bridge-sector approach cells must stay walkable, not only the water crossing',()=>{const m=generateMap(7,'River',0,{layout:'river'}),row=m.sectors.cells.findIndex(r=>r.includes('bridge-ns')),col=m.sectors.cells[row].indexOf('bridge-ns');for(let y=10;y<=13;y++)m.terrain[row*24+y][col*24+8]='crate';assert.ok(validateMap(m).some(e=>e.includes('approach road')));});
