import test from 'node:test';import assert from 'node:assert/strict';
import {createWorld,currentMap,travel,travelReason} from '../dist/tactics/world.js';
import {blankMap} from '../dist/tactics/maps.js';
import {guards,squad,move,stepMovement,refresh} from '../dist/tactics/engine.js';
function gather(s){squad(s).forEach((u,i)=>{u.x=3+(i%2);u.y=4+Math.floor(i/2);});refresh(s);}
test('empty and cleared local maps remain walkable',()=>{const world=createWorld(blankMap()),s=currentMap(world);assert.equal(s.phase,'won');assert.ok(move(s,s.units[0],5,4));while(s.queue.length)stepMovement(s);assert.equal(s.units[0].x,5);assert.equal(s.units[0].ap,12);});
test('travel requires gathered living squad, adjacency, no queue and no combat',()=>{const w=createWorld(),s=currentMap(w);assert.match(travelReason(w,'yard'),/Gather/);gather(s);assert.equal(travelReason(w,'yard'),'');assert.match(travelReason(w,'annex'),/neighboring/);s.queue=[{}];assert.match(travelReason(w,'yard'),/Stop movement/);s.queue=[];s.phase='player';assert.match(travelReason(w,'yard'),/encounter/);});
test('world travel preserves squad HP/ammo and visited map enemies/discovery',()=>{const w=createWorld(),first=currentMap(w);first.units[0].hp=62;first.units[0].ammo.assault=9;first.units[4].hp=0;first.seen.add('20,20');gather(first);assert.ok(travel(w,'yard').ok);let next=currentMap(w);assert.equal(next.units[0].hp,62);assert.equal(next.units[0].ammo.assault,9);next.units[0].hp=47;next.units[0].ammo.assault=2;gather(next);assert.ok(travel(w,'factory').ok);const back=currentMap(w);assert.equal(back.units[0].hp,47);assert.equal(back.units[0].ammo.assault,2);assert.equal(back.units[4].hp,0);assert.ok(back.seen.has('20,20'));});
test('clearing a map permits departure without reviving fallen squad or guards',()=>{const w=createWorld(),s=currentMap(w);s.units[3].hp=0;guards(s).forEach(g=>g.hp=0);gather(s);assert.equal(s.phase,'won');assert.ok(travel(w,'yard').ok);assert.equal(currentMap(w).units[3].hp,0);gather(currentMap(w));assert.ok(travel(w,'factory').ok);assert.equal(guards(currentMap(w)).length,0);assert.equal(squad(currentMap(w)).length,3);});
