import test from 'node:test';
import assert from 'node:assert/strict';
import {blankMap,setTerrain} from '../dist/tactics/maps.js';
import {createGame,canSee,zoneVisible,visibleZones,previewAttack,attack,setStance,refresh,stepEnemy} from '../dist/tactics/engine.js';
import {bulletTrajectory} from '../dist/tactics/projectiles.js';
import {detonate} from '../dist/tactics/explosives.js';
function scene(){const m=blankMap();m.starts=[{x:10,y:10},{x:3,y:3},{x:3,y:5},{x:3,y:7}];m.guards=[{x:15,y:10,species:'pig-foreman',weapon:'rifle'}];const s=createGame(1,m),a=s.units[0],b=s.units[4];s.units.slice(1,4).forEach(u=>u.hp=0);a.heading=0;b.heading=180;a.accuracy=b.accuracy=1000;refresh(s);return {s,a,b};}
test('prone observer cannot see over nearby low cover; standing restores detection and terrain immediately',()=>{const {s,a,b}=scene();s.map[10][12]='crate';refresh(s);assert.ok(canSee(s,a,b));assert.ok(s.visible.has('15,10'));assert.ok(setStance(s,a,'prone'));assert.equal(canSee(s,a,b),false);assert.equal(s.detected.has(b.id),false);assert.equal(s.visible.has('15,10'),false);assert.ok(s.seen.has('15,10'));assert.ok(setStance(s,a,'standing'));assert.ok(s.detected.has(b.id));assert.ok(s.visible.has('15,10'));});
test('window sill hides legs while head and torso remain exposed; hidden aim never spends resources',()=>{const {s,a,b}=scene();s.edges['e:13:10']='window-concrete';refresh(s);assert.deepEqual(visibleZones(s,a,b),['head','weapon','torso']);assert.equal(previewAttack(s,a,b,false,'legs').reason,'Legs hidden by cover');const ap=a.ap,ammo=a.ammo.assault;assert.equal(attack(s,a,b,false,false,'legs'),false);assert.equal(a.ap,ap);assert.equal(a.ammo.assault,ammo);assert.equal(previewAttack(s,a,b,false,'head').ok,true);assert.equal(bulletTrajectory(s,a,b,{accurate:true,zone:'legs',reach:10},()=>0).kind,'wall');});
test('stance changes alter the target body heights; prone targets disappear behind a sill',()=>{const {s,a,b}=scene();s.edges['e:13:10']='window-concrete';b.stance='prone';refresh(s);assert.equal(canSee(s,a,b),false);assert.equal(s.exposed[b.id],undefined);b.stance='kneeling';refresh(s);assert.ok(zoneVisible(s,a,b,'head'));assert.equal(zoneVisible(s,a,b,'legs'),false);});
test('shared sight does not unlock a body part hidden from the selected shooter',()=>{const {s,a,b}=scene();s.edges['e:13:10']='window-concrete';const ally=s.units[1];Object.assign(ally,{hp:100,x:15,y:12,heading:270});refresh(s);assert.ok(s.exposed[b.id].includes('legs'));assert.equal(previewAttack(s,a,b,false,'legs').ok,false);assert.equal(previewAttack(s,ally,b,false,'legs').ok,true);});
test('solid floors block vertical sight for all stances and targeted zones',()=>{const {s,a,b}=scene();Object.assign(b,{x:10,y:10,z:1});setTerrain(s,10,10,1,'floor');for(const stance of ['standing','kneeling','prone']){a.stance=stance;assert.deepEqual(visibleZones(s,a,b),[]);}});
test('enemy chooses an exposed head rather than firing at a hidden torso',()=>{const {s,a,b}=scene();a.stance='kneeling';s.edges['e:11:10']='window-concrete';refresh(s);assert.equal(zoneVisible(s,b,a,'torso'),false);assert.ok(zoneVisible(s,b,a,'head'));s.phase='enemy';s.enemyIndex=b.id;b.ap=7;const ammo=b.ammo.rifle;assert.ok(stepEnemy(s));assert.equal(b.ammo.rifle,ammo-1);assert.equal(s.effect.trajectories[0].zone,'head');});
test('destroying low cover invalidates fog and exposes a target to a prone observer',()=>{const {s,a,b}=scene();s.map[10][12]='crate';a.stance='prone';refresh(s);assert.equal(canSee(s,a,b),false);assert.equal(s.visible.has('15,10'),false);detonate(s,{x:12,y:10,h:1,z:0},{blast:3,damage:220});refresh(s);assert.ok(canSee(s,a,b));assert.ok(s.visible.has('15,10'));assert.ok(s.exposed[b.id].includes('legs'));});
