import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,refresh,attack,endTurn,stepEnemy,medicalCost,stabilize,stabilizePreview,cutFence,cutPreview,equipCutters,movementNeighbors,occupant} from '../dist/tactics/engine.js';
import {blankMap,edgeKey} from '../dist/tactics/maps.js';
import {deathDropArt} from '../dist/tactics/loot-art.js';
function setup(){const m=blankMap();m.guards=[{x:10,y:10,z:0,species:'pig-foreman',weapon:'pistol'}];const s=createGame(1,m,false);s.phase='player';s.units[4].alert=true;return s;}
function down(s,id=1){const u=s.units[id];u.hp=0;u.casualty='bleeding';u.bleedTurns=6;u.ap=0;u.x=4;u.y=4;return u;}
function next(s){assert.equal(endTurn(s),true);s.units[4].ap=0;for(let i=0;i<20&&s.phase==='enemy';i++)stepEnemy(s);}
test('lethal guard damage incapacitates squad for six treatment turns',()=>{const s=setup(),u=s.units[0],g=s.units[4];u.hp=1;g.x=u.x+1;g.y=u.y;g.weapon='hands';g.ap=7;s.phase='enemy';assert.equal(attack(s,g,u,false,true),true);assert.equal(u.casualty,'bleeding');assert.equal(u.bleedTurns,6);assert.equal(u.hp,0);assert.deepEqual(deathDropArt(u),[]);});
test('bleeding lasts five ends and expires on the sixth, even after last guard dies',()=>{const s=setup(),u=down(s);s.units[4].hp=0;refresh(s);assert.equal(s.phase,'player');for(let i=0;i<5;i++){next(s);assert.equal(u.casualty,'bleeding');assert.equal(u.bleedTurns,5-i);}next(s);assert.equal(u.casualty,'dead');assert.equal(s.phase,'won');});
test('medical skill changes AP cost and stabilization consumes one medkit exactly once',()=>{assert.equal(medicalCost({medical:0}),12);assert.equal(medicalCost({medical:100}),3);const s=setup(),p=down(s),u=s.units[0];u.x=3;u.y=4;u.medical=100;u.ap=3;assert.equal(stabilize(s,u,p),true);assert.equal(u.ap,0);assert.equal(u.medkits,0);assert.equal(p.casualty,'stable');assert.equal(p.hp,0);assert.equal(stabilize(s,u,p),false);s.units[4].hp=0;refresh(s);assert.equal(p.hp,0,'clearing the map no longer revives on the spot');assert.equal(s.phase,'player');for(let i=0;i<3;i++)next(s);assert.equal(p.casualty,'stable');next(s);assert.equal(p.hp,5);assert.equal(p.casualty,null);refresh(s);assert.equal(s.phase,'won');});
test('treatment rejects walls, other levels, range and insufficient AP without consuming supplies',()=>{const s=setup(),p=down(s),u=s.units[0];u.x=3;u.y=4;s.edges['e:3:4']='wall';assert.equal(stabilize(s,u,p),false);delete s.edges['e:3:4'];p.z=1;assert.equal(stabilize(s,u,p),false);p.z=0;u.ap=11;assert.equal(stabilize(s,u,p),false);assert.equal(u.medkits,1);assert.equal(u.ap,11);assert.equal(occupant(s,4,4),p);assert.equal(stabilizePreview(s,u,p).cost,12);});
test('cutters make one adjacent chainlink edge passable, charge once, and reject railings',()=>{const s=setup(),u=s.units[0];u.x=3;u.y=4;const edge=edgeKey('e',3,4);s.edges[edge]='fence-chainlink';assert.ok(equipCutters(s,u,1));assert.ok(!movementNeighbors(s,u).some(p=>p.x===4&&p.y===4));u.ap=3;assert.equal(cutFence(s,u,edge),false);u.ap=4;assert.equal(cutFence(s,u,edge),true);assert.equal(u.ap,0);assert.equal(s.edges[edge],'fence-cut');assert.ok(movementNeighbors(s,u).some(p=>p.x===4&&p.y===4));assert.equal(cutFence(s,u,edge),false);s.edges[edge]='fence-railing';assert.equal(cutPreview(s,u,edge).ok,false);});
