import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,canSee,notices,detectionChance,refresh} from '../dist/tactics/engine.js';
import {blankMap,validateMap,passable} from '../dist/tactics/maps.js';
import {terrainVisibility} from '../dist/tactics/visibility.js';
import {woodlandDepth} from '../dist/tactics/woodland.js';
import {createEditor,applyBrush,brushShape,beginStroke,endStroke,undo} from '../dist/tactics/editor-model.js';
function scene(seed=1){const m=blankMap();m.guards=[{x:20,y:10,species:'cow',weapon:'rifle',heading:180}];const s=createGame(seed,m,false),a=s.units[0],g=s.units[4];s.units.slice(1,4).forEach(u=>u.hp=0);Object.assign(a,{x:10,y:10,heading:0});return {s,a,g};}
test('seeing a rear-facing guard does not alert him',()=>{const {s,a,g}=scene();g.heading=0;refresh(s);assert.ok(canSee(s,a,g));assert.ok(s.detected.has(g.id));assert.equal(g.alert,false);assert.equal(s.phase,'explore');});
test('cover, sneaking and prone stance lower acquisition chance',()=>{const {s,a,g}=scene();const open=detectionChance(s,g,a);s.map[10][11]='crate';assert.ok(detectionChance(s,g,a)<open);s.map[10][11]='yard';a.sneaking=true;const sneaking=detectionChance(s,g,a);assert.ok(sneaking<open);a.stance='prone';assert.ok(detectionChance(s,g,a)<sneaking);g.heading=0;assert.equal(detectionChance(s,g,a),0);});
test('acquisition has both outcomes and no refresh or combat RNG rerolls',()=>{let hits=0,misses=0;const {s,a,g}=scene();for(let seed=1;seed<=100;seed++){s.perceptionSeed=seed;g.noticed={};const seen=notices(s,g,a),combatSeed=s.seed;for(let i=0;i<10;i++)assert.equal(notices(s,g,a),seen);assert.equal(s.seed,combatSeed);if(seen)hits++;else misses++;}assert.ok(hits>0&&misses>0);g.heading=0;assert.equal(notices(s,g,a),false);assert.equal(g.noticed[a.id],undefined);});
test('woodland blocks distant contacts and terrain through intervening cells',()=>{const {s,a,g}=scene();g.x=22;assert.ok(canSee(s,a,g));assert.ok(terrainVisibility(s,[a]).has('22,10'));for(let x=12;x<=19;x++)s.map[10][x]='woodland';assert.ok(Math.abs(woodlandDepth(s,a,g)-8)<1e-9);assert.equal(canSee(s,a,g),false);assert.ok(!terrainVisibility(s,[a]).has('22,10'));assert.ok(passable(s,{x:12,y:10}));assert.equal(woodlandDepth(s,{...a,z:1},{...g,z:1}),0);});
test('woodland diagonal lengths and partial endpoints use ray geometry',()=>{const {s}=scene();s.map[10][10]='woodland';assert.equal(woodlandDepth(s,{x:10,y:10},{x:12,y:10}),.5);assert.ok(Math.abs(woodlandDepth(s,{x:10,y:10},{x:12,y:12})-Math.SQRT1_2)<1e-9);});
test('woodland and guard facing survive map roundtrip and editor undo',()=>{const e=createEditor(blankMap());beginStroke(e);assert.equal(applyBrush(e,'woodland',12,12,null),'');endStroke(e);assert.equal(brushShape('woodland'),'rectangle');assert.equal(applyBrush(e,'guard',13,13,null,{heading:45}),'');const m=JSON.parse(JSON.stringify(e.map));assert.deepEqual(validateMap(m),[]);assert.equal(createGame(1,m,false).units[4].heading,45);undo(e);assert.equal(e.map.terrain[12][12],'yard');m.guards[0].heading=360;assert.ok(validateMap(m).length);});
