import test from 'node:test';
import assert from 'node:assert/strict';
import {blankMap,parseMap} from '../dist/tactics/maps.js';
import {WEAPONS,createGame,previewAttack,attack,weaponDamage,stepEnemy} from '../dist/tactics/engine.js';
import {shotgunTrajectories} from '../dist/tactics/projectiles.js';
import {characterArt} from '../dist/tactics/character-art.js';
function scene(weapon,range){const m=blankMap();m.starts=[{x:20,y:20},{x:3,y:3},{x:3,y:5},{x:3,y:7}];m.guards=[{x:20+range,y:20,species:'pig-foreman',weapon:'pistol'}];const s=createGame(1,m),a=s.units[0],b=s.units[4];a.heading=0;a.weapon=weapon;a.ap=12;b.heading=180;return {s,a,b};}
test('every agreed range is executable at its boundary and rejected just past it',()=>{const ranges={hands:1,knife:1,flamethrower:10,pistol:12,shotgun:12,assault:24,smg:20,hmg:28,rifle:24,sniper:36,launcher:22,rpg:40};for(const [w,r]of Object.entries(ranges)){assert.equal(WEAPONS[w].range,r);const {s,a,b}=scene(w,r);assert.equal(previewAttack(s,a,b).ok,true,w);if(!WEAPONS[w].blast){b.x++;assert.equal(previewAttack(s,a,b).reason,'Out of range',w);}}});
test('range-normalized accuracy preserves long-range rifles and weak pistols',()=>{const chance=w=>{const {s,a,b}=scene(w,WEAPONS[w].range);return previewAttack(s,a,b).chance;};assert.equal(chance('pistol'),30);assert.equal(chance('rifle'),72);assert.equal(chance('sniper'),83);assert.equal(chance('assault'),59);assert.equal(chance('launcher'),60);assert.equal(chance('rpg'),60);});
test('flame damage falls with distance while close hits remain lethal',()=>{assert.equal(weaponDamage(WEAPONS.flamethrower,3),180);assert.equal(weaponDamage(WEAPONS.flamethrower,10),45);const {s,a,b}=scene('flamethrower',10);a.accuracy=1000;b.hp=b.maxHp=100;assert.equal(attack(s,a,b),true);assert.equal(b.hp,55);assert.equal(b.burningTurns,3);});
test('one shotgun shell produces six collision paths but charges AP and ammunition once',()=>{const {s,a,b}=scene('shotgun',2);a.accuracy=1000;b.hp=b.maxHp=1000;const ammo=a.ammo.shotgun;assert.equal(attack(s,a,b),true);assert.equal(a.ap,7);assert.equal(a.ammo.shotgun,ammo-1);assert.equal(s.effect.trajectories.length,6);assert.ok(b.hp<1000);assert.ok(characterArt('horse','shotgun').src.includes('weapon-expansion'));});
test('shotgun concentration falls at range, with missed pellets colliding with nearby allies',()=>{let close=0,far=0;for(let seed=1;seed<=80;seed++){for(const range of [2,12]){const {s,a,b}=scene('shotgun',range);let n=seed;const random=()=>((n=(Math.imul(n,1664525)+1013904223)>>>0)/4294967296);const shots=shotgunTrajectories(s,a,b,{accurate:true,reach:18,pellets:6},random);const hits=shots.filter(p=>p.unitId===b.id).length;if(range===2)close+=hits;else far+=hits;}}assert.ok(close>far*2);const {s,a,b}=scene('shotgun',6);Object.assign(s.units[1],{x:21,y:20});const shots=shotgunTrajectories(s,a,b,{accurate:true,reach:18,pellets:6},()=>.5);assert.ok(shots.some(p=>p.unitId===1));});
test('sniper guards can pay for an eight-AP shot and new loadouts survive editor parsing',()=>{const m=blankMap();m.guards=[{x:7,y:4,species:'pig-foreman',weapon:'sniper'}];const s=createGame(1,parseMap(JSON.stringify(m))),g=s.units[4];g.heading=180;g.accuracy=1000;g.alert=true;s.phase='enemy';s.enemyIndex=4;assert.equal(g.maxAp,8);assert.ok(stepEnemy(s));assert.equal(g.ammo.sniper,4);});

test('automatic weapons fire physical three-round bursts and reject insufficient ammunition',()=>{for(const weapon of ['smg','hmg','assault']){const {s,a,b}=scene(weapon,4);a.accuracy=1000;b.hp=b.maxHp=1000;const ammo=a.ammo[weapon];assert.ok(attack(s,a,b,true));assert.equal(a.ap,12-WEAPONS[weapon].cost-2);assert.equal(a.ammo[weapon],ammo-3);assert.equal(s.effect.trajectories.length,3);a.ap=12;a.ammo[weapon]=2;assert.equal(attack(s,a,b,true),false);assert.equal(a.ap,12);assert.equal(a.ammo[weapon],2);assert.ok(characterArt('horse',weapon).src);}});
test('SMG rounds and buckshot pellets share pistol damage and penetration class',()=>{for(const weapon of ['smg','shotgun']){assert.equal(WEAPONS[weapon].damage,WEAPONS.pistol.damage);assert.equal(WEAPONS[weapon].penetrationClass,WEAPONS.pistol.penetrationClass);const {s,a,b}=scene(weapon,2);assert.equal(previewAttack(s,a,b).damage,27);}});
test('new automatic weapons survive editor serialization and have Factory supplies',()=>{for(const weapon of ['smg','hmg']){const m=blankMap();m.guards=[{x:7,y:4,species:'pig-foreman',weapon}];assert.equal(createGame(1,parseMap(JSON.stringify(m))).units[4].weapon,weapon);const s=createGame();assert.ok(s.loot.some(p=>p.items.some(i=>i.type==='weapon'&&i.kind===weapon)));assert.ok(s.loot.some(p=>p.items.some(i=>i.type==='ammo'&&i.kind===weapon)));}});
