import test from 'node:test';
import assert from 'node:assert/strict';
import {blankMap,edgeKey,setTerrain,blockedEdge,passable} from '../dist/tactics/maps.js';
import {createGame,WEAPONS,attackGround,previewAttack,groundTarget,attack} from '../dist/tactics/engine.js';
import {explosiveTrajectory,explosivePreview,detonate} from '../dist/tactics/explosives.js';
import {propAt} from '../dist/tactics/environment.js';
function scene(){const m=blankMap();m.starts=[{x:10,y:10},{x:3,y:3},{x:3,y:5},{x:3,y:7}];m.guards=[{x:18,y:10,species:'pig-foreman',weapon:'pistol'}];const s=createGame(1,m),a=s.units[0];a.heading=0;a.accuracy=1000;return {s,a,b:s.units[4]};}
const fire=(s,a,target,weapon)=>explosiveTrajectory(s,a,target,WEAPONS[weapon],{chance:100},()=>0);
test('rockets collide with the first wall or body; grenades arc over a low wall',()=>{const {s,a,b}=scene();s.edges[edgeKey('e',14,10)]='wall-concrete';const rocket=fire(s,a,b,'rpg');assert.equal(rocket.kind,'wall');assert.equal(rocket.x,14.5);const grenade=fire(s,a,b,'launcher');assert.notEqual(grenade.kind,'wall');assert.ok(grenade.path.some(p=>p.h>2.7));assert.ok(grenade.x>17);delete s.edges[edgeKey('e',14,10)];s.units[1].x=11;s.units[1].y=10;assert.equal(fire(s,a,b,'rpg').unitId,1);});
test('arcs hit ceilings and solid upper floors instead of teleporting through them',()=>{const {s,a,b}=scene();for(let x=10;x<19;x++)setTerrain(s,x,10,1,'floor');const shot=fire(s,a,b,'launcher');assert.equal(shot.kind,'floor');assert.equal(shot.h,3);assert.ok(shot.x<15);});
test('blasts breach wall edges and props, invalidate prop caches, and open navigation',()=>{const {s}=scene(),key=edgeKey('e',14,10);s.edges[key]='wall-concrete';s.props=[{kind:'crate-stack',x:15,y:10,z:0}];assert.ok(propAt(s,15,10));const {blast}=detonate(s,{x:14.5,y:10,h:1,z:0},WEAPONS.rpg);assert.ok(blast.destroyed>=2);assert.equal(s.edges[key],undefined);assert.equal(propAt(s,15,10),undefined);assert.equal(blockedEdge(s,{x:14,y:10},{x:15,y:10}),false);assert.equal(passable(s,{x:15,y:10}),true);});
test('blast damage falls with 3D distance and intact floors shield other levels',()=>{const {s,a,b}=scene();a.x=15;a.y=10;b.x=17;b.y=10;s.units[1].x=15;s.units[1].y=10;s.units[1].z=1;setTerrain(s,15,10,1,'floor');const {hits}=detonate(s,{x:15,y:10,h:.1,z:0},WEAPONS.rpg);assert.ok(hits.find(h=>h.unit===a).damage>hits.find(h=>h.unit===b).damage);assert.ok(!hits.some(h=>h.unit===s.units[1]));assert.equal(s.upper[0]['15,10'],'floor');});
test('beyond effective range has severe scatter, elevation extends launcher reach, and throws are bounded',()=>{const {s,a}=scene();a.weapon='launcher';const t=groundTarget({x:35,y:10,z:0});s.seen.add('35,10');let p=explosivePreview(s,a,t,WEAPONS.launcher);assert.equal(p.ok,true);assert.equal(p.chance,10);a.z=1;p=explosivePreview(s,a,t,WEAPONS.launcher);assert.equal(p.beyond,false);a.z=0;a.weapon='grenade';assert.equal(explosivePreview(s,a,t,WEAPONS.grenade).ok,false);a.weapon='launcher';const shot=explosiveTrajectory(s,a,t,WEAPONS.launcher,{chance:10,beyond:true},()=>.5);assert.ok(Math.hypot(shot.x-t.x,shot.y-t.y)>3);});
test('terrain firing consumes AP and ammunition once, causes strain, and awards kill relief',()=>{const {s,a,b}=scene();a.weapon='rpg';a.social.stress=50;const before=a.ap;assert.equal(attackGround(s,a,{x:18,y:10,z:0}),true);assert.equal(a.ap,before-7);assert.equal(a.ammo.rpg,0);assert.equal(b.hp,0);assert.equal(a.social.stress,35);assert.equal(s.effect.explosions[0].radius,4);assert.equal(attackGround(s,a,{x:18,y:10,z:0}),false);});
test('blast friendly fire damages survivors and records their reaction, without body-zone bonuses',()=>{const {s,a,b}=scene();a.weapon='launcher';s.units[1].x=18;s.units[1].y=11;s.units[1].hp=s.units[1].maxHp=500;s.units[1].weapon='hands';assert.equal(previewAttack(s,a,b,false,'head').damage,140);assert.equal(attack(s,a,b,false,false,'head'),true);assert.ok(s.units[1].hp<500);assert.ok(s.units[1].social.fatigue>0);assert.equal(s.units[1].social.incidents.Yakov.hits,1);});
test('a grenade aimed over a missing upper floor falls until it hits physical ground',()=>{const {s,a}=scene();a.z=1;setTerrain(s,a.x,a.y,1,'floor');const shot=fire(s,a,groundTarget({x:17,y:13,z:1}),'grenade');assert.equal(shot.kind,'floor');assert.ok(Math.abs(shot.h)<1e-6);assert.equal(shot.z,0);});
test('surviving walls block blast damage and near misses do not erase distant scenery',()=>{const {s,a,b}=scene();a.x=10;a.y=10;b.x=13;b.y=10;const wall=edgeKey('e',12,10);s.edges[wall]='wall-concrete';s.props=[{kind:'tree-pine',x:30,y:30,z:0}];const result=detonate(s,{x:10,y:10,h:1,z:0},WEAPONS.grenade);assert.equal(s.edges[wall],'wall-concrete');assert.ok(!result.hits.some(h=>h.unit===b));assert.equal(s.props.length,1);});
test('self damage is possible, and invalid terrain shots never spend resources',()=>{const {s,a}=scene();a.weapon='rpg';const ap=a.ap,ammo=a.ammo.rpg;assert.equal(attackGround(s,a,{x:-1,y:10}),false);s.phase='enemy';assert.equal(attackGround(s,a,{x:11,y:10}),false);s.phase='player';s.queue=[{}];assert.equal(attackGround(s,a,{x:11,y:10}),false);assert.equal(a.ap,ap);assert.equal(a.ammo.rpg,ammo);s.queue=[];assert.equal(attackGround(s,a,{x:11,y:10,z:0}),true);assert.equal(a.hp,0);assert.ok(a.social.fatigue>0);});
