import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {emptyFeaturePlan,requiredConnections,seededFeaturePlan,validatePlannedMap} from '../dist/tactics/feature-plan.js';
import {generateConnectedMap} from '../dist/tactics/block-generator.js';
import {extractBlock,blockCanvas} from '../dist/tactics/blocks.js';
import {parseMap} from '../dist/tactics/maps.js';
const none={north:'none',east:'none',south:'none',west:'none'};
function catalog(){const m=blockCanvas('Empty');m.blockConnections={'0,0':none};const empty=extractBlock(m),road=structuredClone(empty),fence=structuredClone(empty);road.name='Road';road.connections={...none,east:'road',west:'road'};for(let y=9;y<=14;y++)road.terrain[y].fill('ground-asphalt');fence.name='Fence';fence.connections={...none,north:'fence',south:'fence'};for(let y=0;y<24;y++)fence.edges['e:10:'+y]='fence-chainlink';const crossing=JSON.parse(fs.readFileSync('tests/fixtures/road-meet-chain-link-fence.json','utf8'));crossing.connections={north:'fence',east:'road',south:'fence',west:'road'};return [empty,road,fence,crossing];}
test('feature lines run the whole grid and crossings require exact ports',()=>{const p=emptyFeaturePlan();p.rows[8]='road';p.columns[1]='fence';for(let i=0;i<10;i++){assert.equal(requiredConnections(p,i,8).east,'road');assert.equal(requiredConnections(p,1,i).north,'fence');}assert.deepEqual(requiredConnections(p,1,8),{north:'fence',east:'road',south:'fence',west:'road'});});
test('planned map fills the road/fence crossing, keeps all offsets and roundtrips',()=>{const p=emptyFeaturePlan();p.rows[8]='road';p.columns[1]='fence';const m=generateConnectedMap(catalog(),7,p);assert.deepEqual(validatePlannedMap(m),[]);assert.equal(m.guards.length,4);assert.deepEqual(parseMap(JSON.stringify(m)).featurePlan,p);for(let i=0;i<10;i++){assert.equal(m.blockConnections[i+',8'].east,'road');assert.equal(m.blockConnections['1,'+i].north,'fence');}m.terrain[8*24+11][80]='yard';assert.match(validatePlannedMap(m)[0],/Road alignment/);});
test('missing crossing reports exact sector and cannot mutate the plan or library',()=>{const p=emptyFeaturePlan();p.rows[8]='road';p.columns[1]='fence';const blocks=catalog().slice(0,3),before=JSON.stringify(blocks);assert.throws(()=>generateConnectedMap(blocks,7,p),/2,9/);assert.equal(JSON.stringify(blocks),before);});
test('seeded lines deterministic and malformed plans rejected',()=>{assert.deepEqual(seededFeaturePlan(7),seededFeaturePlan(7));assert.equal(seededFeaturePlan(7).rows.filter(t=>t==='road').length,1);assert.throws(()=>generateConnectedMap(catalog(),7,{version:1,rows:[],columns:[]}),/ten rows/);});
test('a straight fence cannot drift between its north and south edges',()=>{const blocks=catalog().slice(0,3),fence=blocks[2];delete fence.edges['e:10:23'];fence.edges['e:11:23']='fence-chainlink';const plan=emptyFeaturePlan();plan.columns[1]='fence';assert.throws(()=>generateConnectedMap(blocks,7,plan),/Missing blocks/);});
