import test from 'node:test';import assert from 'node:assert/strict';
import {blankMap,edgeKey,setTerrain} from '../dist/tactics/maps.js';
import {createGame,refresh,canSee,lineOfSight,navigationPath,move,stepMovement,key,endTurn,stepEnemy} from '../dist/tactics/engine.js';
function field(){const m=blankMap();m.starts=[{x:10,y:100,z:0},{x:9,y:100,z:0},{x:9,y:99,z:0},{x:9,y:101,z:0}];return m;}
test('clear landscape reaches75 while character detection stops at60, with current terrain caches',()=>{const m=field();m.guards=[{x:70,y:100,z:0,species:'cow',weapon:'pistol'},{x:71,y:100,z:0,species:'cow',weapon:'pistol'}];const s=createGame(1,m);s.units[0].heading=0;refresh(s);assert.ok(s.visible.has('85,100'));assert.equal(s.visible.has('86,100'),false);assert.ok(s.detected.has(4));assert.equal(s.detected.has(5),false);s.units[5].x=69;refresh(s);assert.ok(s.detected.has(5));s.units[5].x=71;refresh(s);assert.equal(s.detected.has(5),false);});
test('unknown obstacle variants produce identical initial routes and reveal no endpoint validity',()=>{const a=field(),b=field();b.terrain[100][120]='crate';b.edges[edgeKey('e',115,100)]='wall';const sa=createGame(1,a),sb=createGame(1,b);assert.equal(sa.seen.has('120,100'),false);assert.deepEqual(navigationPath(sa,sa.units[0],120,100),navigationPath(sb,sb.units[0],120,100));assert.ok(move(sb,sb.units[0],120,100));});
test('navigation reaches unknown destination and reroutes around newly revealed obstacles',()=>{const m=field();m.terrain[100][90]='crate';const s=createGame(1,m),u=s.units[0];assert.ok(move(s,u,94,100));let n=0;while(s.queue.length&&n++<150)stepMovement(s);assert.ok(n<150);assert.deepEqual([u.x,u.y],[94,100]);assert.equal(u.ap,12);assert.ok(s.seen.has('90,100'));});
test('newly revealed blocked destination stops without claiming arrival',()=>{const m=field();m.terrain[100][90]='crate';const s=createGame(1,m),u=s.units[0];assert.ok(move(s,u,90,100));let n=0;while(s.queue.length&&n++<100)stepMovement(s);assert.ok(n<100);assert.notEqual(u.x,90);assert.equal(s.queue.length,0);});
test('spotting a distant guard stops movement without automatically alerting him',()=>{const m=field();m.guards=[{x:80,y:100,z:0,species:'cow',weapon:'pistol'}];const s=createGame(1,m),u=s.units[0];assert.equal(s.phase,'explore');assert.ok(move(s,u,120,100));let n=0;while(s.queue.length&&n++<30)stepMovement(s);assert.equal(u.x,20);assert.equal(s.phase,'explore');assert.equal(s.units[4].alert,false);assert.equal(s.queue.length,0);assert.equal(u.ap,12);});
test('long combat orders move only affordable steps and never resume next turn',()=>{const m=field();m.guards=[{x:220,y:220,z:0,species:'cow',weapon:'pistol'}];const s=createGame(1,m),u=s.units[0];s.phase='player';s.units[4].alert=true;u.ap=5;assert.ok(move(s,u,120,100));while(s.queue.length)stepMovement(s);assert.equal(u.x,12);assert.equal(u.ap,1);endTurn(s);s.enemyIndex=s.units.length;stepEnemy(s);assert.equal(s.queue.length,0);assert.equal(u.x,12);});
test('terrain caches invalidate on walls and agree with exact LOS through window openings',()=>{const s=createGame(1,field()),u=s.units[0];s.edges[edgeKey('e',11,100)]='wall';refresh(s);assert.equal(s.visible.has('12,100'),false);s.edges[edgeKey('e',11,100)]='window-concrete';refresh(s);for(const [x,y]of [[12,100],[12,101],[14,100],[14,102]])assert.equal(s.visible.has(key(x,y)),s.units.slice(0,4).some(a=>lineOfSight(s,a,{x,y,z:0})));});
