import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as T from '../dist/tactics/vendor/three.module.js';
import {WEAPONS} from '../dist/tactics/engine.js';
import {createWeaponModel,WEAPON_MODELS} from '../dist/tactics/weapon-models.js';
import {createLightHorse} from '../dist/tactics/horse-light-model.js';
const data=JSON.parse(fs.readFileSync(new URL('../dist/tactics/horse-10k-data.json',import.meta.url)));
function distanceToMeshes(point,meshes){let nearest=Infinity;const a=new T.Vector3(),b=new T.Vector3(),c=new T.Vector3(),closest=new T.Vector3(),tri=new T.Triangle(a,b,c);for(const mesh of meshes){const g=mesh.geometry,p=g.attributes.position;if(!p)continue;const count=g.index?.count||p.count;for(let i=0;i<count;i+=3){for(const [k,v] of [[0,a],[1,b],[2,c]])v.fromBufferAttribute(p,g.index?g.index.getX(i+k):i+k).applyMatrix4(mesh.matrixWorld);if(tri.getArea()<1e-12)continue;tri.closestPointToPoint(point,closest);nearest=Math.min(nearest,closest.distanceTo(point));}}return nearest;}
test('model catalog covers every gameplay weapon with suitable contact semantics',()=>{assert.deepEqual(Object.keys(WEAPON_MODELS).sort(),Object.keys(WEAPONS).sort());for(const id of Object.keys(WEAPON_MODELS)){const w=createWeaponModel(id);try{assert.equal(w.id,id);assert.ok(w.triangles<3000);if(id==='hands'){assert.equal(w.parts.length,0);assert.equal(w.carry.hands.length,0);}else assert.ok(w.anchors.grip);if(['knife','grenade','hands'].includes(id))assert.equal(w.anchors.muzzle,undefined);else assert.ok(w.anchors.muzzle&&w.muzzleMesh);if(id==='knife')assert.ok(w.anchors.tip);if(id==='grenade')assert.ok(w.anchors.release);}finally{w.dispose();}}});
test('every carry meets actual weapon surfaces and skinned hand geometry; barrel mouths follow heading',()=>{const horse=createLightHorse(data);try{for(const id of Object.keys(WEAPON_MODELS)){const w=createWeaponModel(id);horse.equipWeapon(w);try{for(const heading of [0,37,135,-90]){horse.pose('carry',heading);const d=horse.diagnostics();assert.equal(d.contacts.length,w.carry.hands.length,id);assert.ok(Math.abs(d.min[1])<1e-7);for(const contact of d.contacts){assert.ok(contact.error<1e-6);const point=new T.Vector3(...contact.grip),distance=distanceToMeshes(point,w.parts.filter(m=>m!==w.hose));assert.ok(distance<.026,`${id} ${contact.side} weapon surface gap ${distance}`);const hand=horse.parts.find(p=>p.name==='forearm and hand '+contact.side),p=hand.geometry.attributes.position;let nearest=Infinity;for(let i=0;i<p.count;i++){const v=new T.Vector3().fromBufferAttribute(p,i);if(v.y>.78)continue;hand.applyBoneTransform(i,v);v.applyMatrix4(hand.matrixWorld);nearest=Math.min(nearest,v.distanceTo(point));}assert.ok(nearest<.015,`${id} hand surface ${nearest}`);}if(w.muzzleMesh){const anchor=w.anchors.muzzle.getWorldPosition(new T.Vector3()),opening=new T.Vector3().fromBufferAttribute(w.muzzleMesh.geometry.attributes.position,0).applyMatrix4(w.muzzleMesh.matrixWorld);assert.ok(anchor.distanceTo(opening)<.0002,id+' muzzle cap center');}if(w.hose){for(const [name,end] of [['hoseOut',0],['hoseIn',18*7]]){const anchor=w.anchors[name].getWorldPosition(new T.Vector3()),p=w.hose.geometry.attributes.position,v=new T.Vector3();for(let k=0;k<6;k++)v.add(new T.Vector3().fromBufferAttribute(p,end+k));v.multiplyScalar(1/6).applyMatrix4(w.hose.matrixWorld);assert.ok(v.distanceTo(anchor)<1e-6,'hose endpoint '+name);}}}}finally{horse.equipWeapon();w.dispose();}}}finally{horse.dispose();}});
test('backpack and hose detach completely when switching to bare hands',()=>{const horse=createLightHorse(data),flame=createWeaponModel('flamethrower'),hands=createWeaponModel('hands');try{horse.equipWeapon(flame);horse.pose('carry');assert.ok(flame.mount.parent?.isBone);assert.equal(flame.hose.parent,horse.root);assert.ok(flame.parts.filter(p=>p.name==='fuel cylinder').length===2);horse.equipWeapon(hands);horse.pose('carry');assert.equal(flame.root.parent,null);assert.equal(flame.mount.parent,null);assert.equal(flame.hose.parent,null);assert.equal(horse.diagnostics().contacts.length,0);}finally{horse.equipWeapon();flame.dispose();hands.dispose();horse.dispose();}});
