"""Rebuild calibrated crop bounds for the additional environment collections."""
import json
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
assets = root / 'dist/assets/environment'
# One file per scenery group of docs/tactics/SCENERY-PORT-HANDOFF.md, so two parcels never
# regenerate the same catalog. A group with no artwork yet emits an empty object.
GROUPS = ['lighting', 'towers', 'cargo', 'furniture', 'machines', 'conveyor', 'vehicles']
HEADER = '// Generated by tools/catalog-environment.py; alpha >= 64.'


def bounds(path):
    alpha = Image.open(path).convert('RGBA').getchannel('A')
    return alpha.point(lambda a: 255 if a >= 64 else 0).getbbox()


def emit(path, name, entries):
    body = HEADER + '\nexport const ' + name + ' = ' + json.dumps(entries, indent=2) + ';\n'
    path.write_text(body, encoding='utf-8', newline='\n')


art = {}
for folder in ['facility', 'hospital', 'containers', 'loot']:
    for path in sorted((assets / folder).glob('*.png')):
        art[path.stem] = {'file': f'{folder}/{path.name}', 'crop': bounds(path)}
for name in ['tree-broadleaf', 'tree-pine', 'bush', 'reeds']:
    path = assets / 'foliage' / (name + '.png')
    art[name] = {'file': f'foliage/{path.name}', 'crop': bounds(path)}
path = assets / 'fence-chainlink-cut.png'
for name in ['tree-broadleaf', 'tree-pine']:
    art[name + '-large'] = dict(art[name])
for name in ['roof-corrugated-flat', 'roof-corrugated-sloped', 'roof-flat-parapet']:
    roof = assets / (name + '.png')
    art[name] = {'file': roof.name, 'crop': bounds(roof)}
art['fence-cut'] = {'file': path.name, 'crop': bounds(path)}
# Pixel anchors at each barrier's foot, plus visible post height; mapped onto either tile edge.
for key in ['jail-bars', 'jail-door-closed']:
    art[key].update(baseline=[350, 1190, 907, 950, 900], height=62)
art['fence-cut'].update(baseline=[230, 1165, 1110, 694, 530], height=44)
emit(root / 'dist/tactics/prop-art.js', 'PROP_ART', art)

for group in GROUPS:
    folder = assets / group
    entries = {}
    for path in (sorted(folder.glob('*.png')) if folder.is_dir() else []):
        entries[path.stem] = {'file': f'{group}/{path.name}', 'crop': bounds(path)}
    emit(root / f'dist/tactics/prop-art-{group}.js', 'GROUP_PROP_ART', entries)
