param([string]$SourceList='art/body-sources.json')
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
Add-Type -TypeDefinition @'
using System;
using System.Drawing;
public static class BodyBounds {
 public static int[] Find(Bitmap b) {
  int x0=b.Width,y0=b.Height,x1=-1,y1=-1,empty=0,solid=0;
  for(int y=0;y<b.Height;y++)for(int x=0;x<b.Width;x++){
   int a=b.GetPixel(x,y).A;
   if(a==0)empty++;
   if(a>20){x0=Math.Min(x0,x);x1=Math.Max(x1,x);y0=Math.Min(y0,y);y1=Math.Max(y1,y);solid++;}
  }
  if(empty==0||solid==0)throw new Exception("Sprite must have transparent and visible pixels");
  return new int[]{x0,y0,x1,y1};
 }
}
'@ -ReferencedAssemblies System.Drawing.Common,System.Drawing.Primitives
$root=Split-Path $PSScriptRoot -Parent
$entries=Get-Content -Raw (Join-Path $root $SourceList) | ConvertFrom-Json
$frames=@()
foreach($entry in $entries){
 $source=Join-Path $root $entry.source
 if(!(Test-Path -LiteralPath $source)){continue}
 $img=[System.Drawing.Bitmap]::new($source)
 try {
  $b=[BodyBounds]::Find($img)
  $targetHeight=[Math]::Min(160,236*($b[3]-$b[1]+1)/($b[2]-$b[0]+1))
  $scale=$targetHeight/($b[3]-$b[1]+1)
  $w=($b[2]-$b[0]+1)*$scale
  $frameWidth=[int]([Math]::Ceiling([Math]::Max(384,$w+24)/128)*128)
  $relative='bodies/'+$entry.outfit+'/'+$entry.species+'-side.png'
  $destination=Join-Path $root ('dist/assets/characters/'+$relative)
  New-Item -ItemType Directory -Force (Split-Path $destination -Parent) | Out-Null
  $dest=[System.Drawing.Bitmap]::new($frameWidth,256,[System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $g=[System.Drawing.Graphics]::FromImage($dest)
  try {
   $g.InterpolationMode=[System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
   $g.DrawImage($img,[System.Drawing.RectangleF]::new(($frameWidth-$w)/2,244-$targetHeight,$w,$targetHeight),[System.Drawing.RectangleF]::new($b[0],$b[1],$b[2]-$b[0]+1,$b[3]-$b[1]+1),[System.Drawing.GraphicsUnit]::Pixel)
   $dest.Save($destination,[System.Drawing.Imaging.ImageFormat]::Png)
  } finally {$g.Dispose();$dest.Dispose()}
  $frames+=@{species=$entry.species;outfit=$entry.outfit;pose='side';src='../assets/characters/'+$relative;width=$frameWidth;height=256;anchor=@(($frameWidth/2),244);contentHeight=$targetHeight}
  $entry.status='exported'
 } finally {$img.Dispose()}
}
$entries | ConvertTo-Json -Depth 6 | Set-Content -Encoding utf8 (Join-Path $root $SourceList)
$frames | ConvertTo-Json -Depth 6 | Set-Content -Encoding utf8 (Join-Path $root 'dist/assets/characters/bodies/manifest.json')
$frameJson=ConvertTo-Json -InputObject @($frames) -Depth 6 -Compress
("// Generated by tools/prepare-bodies.ps1.`nexport const BODY_FRAMES="+$frameJson+";" ) | Set-Content -Encoding utf8 (Join-Path $root 'dist/tactics/body-frames.js')
Write-Output ("Exported {0} / {1} sprites" -f $frames.Count,$entries.Count)
